{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flutternetwork.wifi.wifi_scan",
    "module": "wifi_scan_release",
    "version": "v1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_release-v1.1.0.aar",
          "url": "wifi_scan_release-v1.1.0.aar",
          "size": 19117,
          "sha512": "a59faa60d38b185d8ce7fece0ab1c0fc8a4227b11adc62c97a8b2bd66bb1eb31a1759a1bc70078a3999f7ec41b748ef1906a5c5f3df2db83d5c0afbcca1f0701",
          "sha256": "585cc7c4c2ed7a333f5830cf929e37770906de0f2abce2ee3641c4968241c2f5",
          "sha1": "0c604c40c9074427627af21f5583352fdeba094d",
          "md5": "ccc333bc38944020dcb6949984376bf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_release-v1.1.0.aar",
          "url": "wifi_scan_release-v1.1.0.aar",
          "size": 19117,
          "sha512": "a59faa60d38b185d8ce7fece0ab1c0fc8a4227b11adc62c97a8b2bd66bb1eb31a1759a1bc70078a3999f7ec41b748ef1906a5c5f3df2db83d5c0afbcca1f0701",
          "sha256": "585cc7c4c2ed7a333f5830cf929e37770906de0f2abce2ee3641c4968241c2f5",
          "sha1": "0c604c40c9074427627af21f5583352fdeba094d",
          "md5": "ccc333bc38944020dcb6949984376bf4"
        }
      ]
    }
  ]
}
