{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.googleapiavailability",
    "module": "google_api_availability_android_debug",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "google_api_availability_android_debug-2.2.0rc1.aar",
          "url": "google_api_availability_android_debug-2.2.0rc1.aar",
          "size": 10779,
          "sha512": "e512fdc346eed85903b1fe13424efb2c21477041baa93a1bacf712b2c08433c341944cb51f7e0faea108ac6c305bd78e9cf47c5f63414193a32bc5b1e277ef21",
          "sha256": "d0ea48e68855661c12f791d300d22e82ed8e63262f7947999972c81f6dcebe06",
          "sha1": "18de874ce828a8048ed2ef97c3625288ff4f7d89",
          "md5": "7c7836332c43b34563cdbab7ea7a8b85"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "google_api_availability_android_debug-2.2.0rc1.aar",
          "url": "google_api_availability_android_debug-2.2.0rc1.aar",
          "size": 10779,
          "sha512": "e512fdc346eed85903b1fe13424efb2c21477041baa93a1bacf712b2c08433c341944cb51f7e0faea108ac6c305bd78e9cf47c5f63414193a32bc5b1e277ef21",
          "sha256": "d0ea48e68855661c12f791d300d22e82ed8e63262f7947999972c81f6dcebe06",
          "sha1": "18de874ce828a8048ed2ef97c3625288ff4f7d89",
          "md5": "7c7836332c43b34563cdbab7ea7a8b85"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_api_availability_android_debug-2.2.0rc1-sources.jar",
          "url": "google_api_availability_android_debug-2.2.0rc1-sources.jar",
          "size": 4340,
          "sha512": "d3df5efb2e69693c10aa20233be11edb72b79729a86317bfd96bb270a3d17bb4f9ba06bc09dd1338b01f6b8132bbb44ddbc7ad867358fd1e0fa91a46ed20497b",
          "sha256": "1d2da8bcf52c79efecd43e2d2306565c1aa43a95c279c04324fb6aa8012eafd9",
          "sha1": "4396701311008b7311eabe67030bba81fbe42c2a",
          "md5": "82113b662a4e791d8bf1804d60a14de5"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_api_availability_android_debug-2.2.0rc1-javadoc.jar",
          "url": "google_api_availability_android_debug-2.2.0rc1-javadoc.jar",
          "size": 269338,
          "sha512": "5dfd3d2be5a95cef0ce353394505aabfbbce11ddab524fee43c759f988de3aa9126a56c30c35d99c7f1998f5440821fe663b699bf03d1651b29cd973bbb42691",
          "sha256": "4416d1e80d44a9ea672c90aa884923b99e9cbb70443bfb017ba12dbcc5affedf",
          "sha1": "1dbced460f566033149b609476519eaaae1c1beb",
          "md5": "a4010b0c3437d7f9725199e256ba7a8d"
        }
      ]
    }
  ]
}
