{
  "formatVersion": "1.1",
  "component": {
    "group": "com.alternadom.wifiiot",
    "module": "wifi_iot_profile",
    "version": "v1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_profile-v1.1.0.aar",
          "url": "wifi_iot_profile-v1.1.0.aar",
          "size": 38803,
          "sha512": "112978b3f2bdfa072aad2adb9f5a03b0ec65dbabaf68ee1968f264b50a9f42650f5a786a47a2bf18c9b972f763455a2c2cadb0977917eaea03ae851544bfb212",
          "sha256": "6088ae4b4ddd575829ed77474683917f84efc12a12db208e8dec4684f1ecdc39",
          "sha1": "5dfb24566c281ba4c8b232d5a413af4eeeb2f5a6",
          "md5": "524599f25b41ca0ecb1b6a3f84a4e2c1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_profile-v1.1.0.aar",
          "url": "wifi_iot_profile-v1.1.0.aar",
          "size": 38803,
          "sha512": "112978b3f2bdfa072aad2adb9f5a03b0ec65dbabaf68ee1968f264b50a9f42650f5a786a47a2bf18c9b972f763455a2c2cadb0977917eaea03ae851544bfb212",
          "sha256": "6088ae4b4ddd575829ed77474683917f84efc12a12db208e8dec4684f1ecdc39",
          "sha1": "5dfb24566c281ba4c8b232d5a413af4eeeb2f5a6",
          "md5": "524599f25b41ca0ecb1b6a3f84a4e2c1"
        }
      ]
    }
  ]
}
