{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flutternetwork.wifi.wifi_scan",
    "module": "wifi_scan_release",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_release-2.1.0.aar",
          "url": "wifi_scan_release-2.1.0.aar",
          "size": 19120,
          "sha512": "d05f4495bb2f4b7f29d68ce47bcfb8c8140fa413bf64f96091770dfbeb87e2e653287670d7069f3b04bee6e8e3f91891be7eec8bd863297ee71cf6987321dc20",
          "sha256": "a99d9f3f47b1135312cfe701ce75c545093de7bb57045612d8a38552d1fcb361",
          "sha1": "d87c0feeffbcbd8b040c390df598aa64755817c9",
          "md5": "99c0161cb956f5f649e3d9423cfd9cc2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_release-2.1.0.aar",
          "url": "wifi_scan_release-2.1.0.aar",
          "size": 19120,
          "sha512": "d05f4495bb2f4b7f29d68ce47bcfb8c8140fa413bf64f96091770dfbeb87e2e653287670d7069f3b04bee6e8e3f91891be7eec8bd863297ee71cf6987321dc20",
          "sha256": "a99d9f3f47b1135312cfe701ce75c545093de7bb57045612d8a38552d1fcb361",
          "sha1": "d87c0feeffbcbd8b040c390df598aa64755817c9",
          "md5": "99c0161cb956f5f649e3d9423cfd9cc2"
        }
      ]
    }
  ]
}
