{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_debug",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_debug-2.2.0rc1.aar",
          "url": "sqflite_android_debug-2.2.0rc1.aar",
          "size": 45036,
          "sha512": "91df861d38b91de8983c61e8ad7834a5c247c3ca174993e26b66a5eb8cf4a06b6fc96a66e0ea6e20c100e28320ef6c7c577cfa41c03b3fb54bb8dca0792cad17",
          "sha256": "7279e09b7b25a4fb74f1f06d6ddf73d04c8e57d33d656314f5cc341ca5a08fd3",
          "sha1": "67158a188632c00ab465cb573478a3591e19fe37",
          "md5": "ec6b7dcbfb1fb4b910811b271ff9cb03"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_debug-2.2.0rc1.aar",
          "url": "sqflite_android_debug-2.2.0rc1.aar",
          "size": 45036,
          "sha512": "91df861d38b91de8983c61e8ad7834a5c247c3ca174993e26b66a5eb8cf4a06b6fc96a66e0ea6e20c100e28320ef6c7c577cfa41c03b3fb54bb8dca0792cad17",
          "sha256": "7279e09b7b25a4fb74f1f06d6ddf73d04c8e57d33d656314f5cc341ca5a08fd3",
          "sha1": "67158a188632c00ab465cb573478a3591e19fe37",
          "md5": "ec6b7dcbfb1fb4b910811b271ff9cb03"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_debug-2.2.0rc1-sources.jar",
          "url": "sqflite_android_debug-2.2.0rc1-sources.jar",
          "size": 23663,
          "sha512": "8fab4715d7e3d96747ef1de92c03dff003c7f72e23c9a2bada2ac1a0daad359c22677107af7f95eed76447893685131f72c8c4575f646eb6db0cd0d6960f5c63",
          "sha256": "a51229e1462df34685f523fbb152893e17abfe4811849e1295d6c0bf25477e3e",
          "sha1": "a594f17941e467782009913a999b4812257c41f5",
          "md5": "5f4db26adb3c92e861735d64021ac12f"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_debug-2.2.0rc1-javadoc.jar",
          "url": "sqflite_android_debug-2.2.0rc1-javadoc.jar",
          "size": 339923,
          "sha512": "0ac0f5767fac8c31e778a235318869c25e9d6000a680dea044e7e97a092f5711def30b7258a3b676f8d354a7fd2cf7204b9f4ea532bbc1248e07d788977c95fe",
          "sha256": "9b474880408539f3e09503ba06782e70825d2da9cd4af78c276c80a9db9dc0d2",
          "sha1": "58284e26af0474a5720f3c319eeeb6a2fa9d6ce7",
          "md5": "94dd2db8c5a440b8e8fced8f07c13bde"
        }
      ]
    }
  ]
}
