{
  "formatVersion": "1.1",
  "component": {
    "group": "io.adaptant.labs.flutter_windowmanager",
    "module": "flutter_windowmanager_debug",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_debug-2.1.2.aar",
          "url": "flutter_windowmanager_debug-2.1.2.aar",
          "size": 5877,
          "sha512": "ebbc0e5e49367a3ae9213d1d320afd55cb392cd522af3070d72897c16bc1f3bedb343c925fb711253c555549210b3f7ffc3bd4e48e058fbe4dd3bc02710821f5",
          "sha256": "249c9424600ad393fa9bee24fc7c56ca4f30c2311b5d002abe54c26bd3344154",
          "sha1": "547a1fe27c1e4589ab6505f8cc90ff0bd1747bad",
          "md5": "97022d775414f25b0aaeecbce9b5b3ca"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_debug-2.1.2.aar",
          "url": "flutter_windowmanager_debug-2.1.2.aar",
          "size": 5877,
          "sha512": "ebbc0e5e49367a3ae9213d1d320afd55cb392cd522af3070d72897c16bc1f3bedb343c925fb711253c555549210b3f7ffc3bd4e48e058fbe4dd3bc02710821f5",
          "sha256": "249c9424600ad393fa9bee24fc7c56ca4f30c2311b5d002abe54c26bd3344154",
          "sha1": "547a1fe27c1e4589ab6505f8cc90ff0bd1747bad",
          "md5": "97022d775414f25b0aaeecbce9b5b3ca"
        }
      ]
    }
  ]
}
