{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-2.5.0.aar",
          "url": "path_provider_android_profile-2.5.0.aar",
          "size": 12642,
          "sha512": "32c76d0cf4c1cf9d5c94f98fb232d87fc20e6d71c85161b1611da85e849cd06ef0243f672237b862370873cd41a4ea28ef9835fe877307e7692cdd2a3e8a56b7",
          "sha256": "f50dfcbc4e0495e9fd313645e162935945080e7a0605f9f0bb4a24d999cfe651",
          "sha1": "db800d0a49c89ed06901beb5868139aab417dfed",
          "md5": "9acfea012f64bac1c7a16d24b7be36d9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-2.5.0.aar",
          "url": "path_provider_android_profile-2.5.0.aar",
          "size": 12642,
          "sha512": "32c76d0cf4c1cf9d5c94f98fb232d87fc20e6d71c85161b1611da85e849cd06ef0243f672237b862370873cd41a4ea28ef9835fe877307e7692cdd2a3e8a56b7",
          "sha256": "f50dfcbc4e0495e9fd313645e162935945080e7a0605f9f0bb4a24d999cfe651",
          "sha1": "db800d0a49c89ed06901beb5868139aab417dfed",
          "md5": "9acfea012f64bac1c7a16d24b7be36d9"
        }
      ]
    }
  ]
}
