{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_debug",
    "version": "v1.1.1h",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.1.1h.aar",
          "url": "flutter_debug-v1.1.1h.aar",
          "size": 48907681,
          "sha512": "c9346504970424749d089a3b62dc47e34c0c0994b2e7ec32450af539b13dbda51bfb3bcfa152397e939b181e5f8c9acd92618bc3b034ff132b1f7332298722f4",
          "sha256": "e0b7c9daa377d44c3d64f30c0c1de81a705daf60950208d85d09d14db8000ed8",
          "sha1": "3ac8dedfdfd672d83ff819f762b527825ab29a19",
          "md5": "8c57de03459d729ed1acc4b2d5fa3503"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v1.1.1h"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.1.1h.aar",
          "url": "flutter_debug-v1.1.1h.aar",
          "size": 48907681,
          "sha512": "c9346504970424749d089a3b62dc47e34c0c0994b2e7ec32450af539b13dbda51bfb3bcfa152397e939b181e5f8c9acd92618bc3b034ff132b1f7332298722f4",
          "sha256": "e0b7c9daa377d44c3d64f30c0c1de81a705daf60950208d85d09d14db8000ed8",
          "sha1": "3ac8dedfdfd672d83ff819f762b527825ab29a19",
          "md5": "8c57de03459d729ed1acc4b2d5fa3503"
        }
      ]
    }
  ]
}
