{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_debug",
    "version": "v1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.1.2.aar",
          "url": "flutter_debug-v1.1.2.aar",
          "size": 47070145,
          "sha512": "15c888675d438bb1a2705fb8de091ab82504866d1149a442fdbc8035fcedf477f73ca310ded9361d95bf1c4b6bc3dca568e819a0b0cd0ec60abff13126eb5aa5",
          "sha256": "9b26df70a66af9232e33925e2fa29d24da33731bc2fdaea9707c2df05e9c47b1",
          "sha1": "879096748bc81a5922cae052d55e5837f493c3ad",
          "md5": "42a228d9cd9f31f5bf90572a436b67e1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.1.2.aar",
          "url": "flutter_debug-v1.1.2.aar",
          "size": 47070145,
          "sha512": "15c888675d438bb1a2705fb8de091ab82504866d1149a442fdbc8035fcedf477f73ca310ded9361d95bf1c4b6bc3dca568e819a0b0cd0ec60abff13126eb5aa5",
          "sha256": "9b26df70a66af9232e33925e2fa29d24da33731bc2fdaea9707c2df05e9c47b1",
          "sha1": "879096748bc81a5922cae052d55e5837f493c3ad",
          "md5": "42a228d9cd9f31f5bf90572a436b67e1"
        }
      ]
    }
  ]
}
