{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_release",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-2.0.1.aar",
          "url": "camera_android_release-2.0.1.aar",
          "size": 120104,
          "sha512": "84422d9de34ca5dc799a9bad276a9d6c1c5c239ed0e7de5ecd346f7773bd37b3b58d1f4cbc08b7c714415a679bd876f0106c158d44a20ba61fa4857ef72affdf",
          "sha256": "e56d18bad861133aa6397c8119c5248cdf83c89dd1dc28be8900d0c94abf54af",
          "sha1": "29b5084b85d2921e0fb5f239d40d57903c652c38",
          "md5": "b06db1e025058ea85160aebe9e2f62c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-2.0.1.aar",
          "url": "camera_android_release-2.0.1.aar",
          "size": 120104,
          "sha512": "84422d9de34ca5dc799a9bad276a9d6c1c5c239ed0e7de5ecd346f7773bd37b3b58d1f4cbc08b7c714415a679bd876f0106c158d44a20ba61fa4857ef72affdf",
          "sha256": "e56d18bad861133aa6397c8119c5248cdf83c89dd1dc28be8900d0c94abf54af",
          "sha1": "29b5084b85d2921e0fb5f239d40d57903c652c38",
          "md5": "b06db1e025058ea85160aebe9e2f62c5"
        }
      ]
    }
  ]
}
