{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_profile",
    "version": "v2.0.0rc5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-v2.0.0rc5.aar",
          "url": "flutter_profile-v2.0.0rc5.aar",
          "size": 39948373,
          "sha512": "bf516eb2f6a8a71af9f082bdc2357b6381f9607c0216f981b2f6ecc4bdb74785d30729ea157c1d94e69649906c775cc1d2d6ddc6095a280912a7f7de1eed5860",
          "sha256": "0fcf1380efa95773066de15516d124eaa0b01d921a549197c0957ad09247d947",
          "sha1": "52234753d6c16a6efd2876572fda695785cae5a5",
          "md5": "f24df0408a805672d3e1d984102cadc2"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "v2.0.0rc5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-v2.0.0rc5.aar",
          "url": "flutter_profile-v2.0.0rc5.aar",
          "size": 39948373,
          "sha512": "bf516eb2f6a8a71af9f082bdc2357b6381f9607c0216f981b2f6ecc4bdb74785d30729ea157c1d94e69649906c775cc1d2d6ddc6095a280912a7f7de1eed5860",
          "sha256": "0fcf1380efa95773066de15516d124eaa0b01d921a549197c0957ad09247d947",
          "sha1": "52234753d6c16a6efd2876572fda695785cae5a5",
          "md5": "f24df0408a805672d3e1d984102cadc2"
        }
      ]
    }
  ]
}
