{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0.aar",
          "size": 2494,
          "sha512": "b48ec869149ee5c7d76c12ef38da88f55fca71496352b27a35ca38215a6767163273d12bb7d454f80df8bd5620da29f7d6e7f16403b812433ab9e058707432d4",
          "sha256": "16fc5aaebb64858cbfaf303aad39e2afa85711c2c36f7244aefe827dfc09cd30",
          "sha1": "df3b2bc4926b4b5454dba58fcb610ce940792468",
          "md5": "598f3e66df391468a15563476ba32d9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0.aar",
          "size": 2494,
          "sha512": "b48ec869149ee5c7d76c12ef38da88f55fca71496352b27a35ca38215a6767163273d12bb7d454f80df8bd5620da29f7d6e7f16403b812433ab9e058707432d4",
          "sha256": "16fc5aaebb64858cbfaf303aad39e2afa85711c2c36f7244aefe827dfc09cd30",
          "sha1": "df3b2bc4926b4b5454dba58fcb610ce940792468",
          "md5": "598f3e66df391468a15563476ba32d9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0-sources.jar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0-sources.jar",
          "size": 2659,
          "sha512": "d848b9ac3a80bd88694f7d35de2abc2866f65393d53caa1f49513063e17fe497a4b7e1ed09dc3736f529a166f1491dfb78c703a51f0fe0950082488869f2b352",
          "sha256": "2930f0a83f74dc7a57026b471c4443a3e5cb4f8b5f80bf45d161dd31675194c7",
          "sha1": "82b1c36d1af62197547e6c132ae64f520e3ad7a7",
          "md5": "fb7b3ee0458fe0f3ec0a8116c68f72ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0-javadoc.jar",
          "size": 269831,
          "sha512": "6eeb099d197827dd1425e1971bdfca63cf3a2ef9e47e5b12a6251be032ea44d90cb34af438041a52e1f9262e86a804609f609ce52d638ab208a9b5378a8fe40d",
          "sha256": "591b3470485a19e5b27e7cc6c841828d019cca16ed4f65ee227657b0c9ee7584",
          "sha1": "3db8af3f4ca4ec876ca5dfe5ab5fe7ae0bef6db7",
          "md5": "4c9c649339f2cd8110945a0449fa41cb"
        }
      ]
    }
  ]
}
