{
  "formatVersion": "1.1",
  "component": {
    "group": "com.danieldallos.storeredirect",
    "module": "store_redirect_profile",
    "version": "v2.0.0rc7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_profile-v2.0.0rc7.aar",
          "url": "store_redirect_profile-v2.0.0rc7.aar",
          "size": 4872,
          "sha512": "b76bafba0ba3cdd62e601d368e1ed7b82da9a29daa53c90b4ad3d65de420983ec40b6a8702df8426c07aadc9b2bd99ee7cb9e59998097a1249a1d9ff3fc802fd",
          "sha256": "e2185732ce81e00d30ec05e000951519fcaacf21ae9d0f9476ed6e88b29c7b47",
          "sha1": "8022f1bb8edf03ef5c122bb79c16fcd323d7ed92",
          "md5": "cac3e80414c415b92e3a995b42d3ca9c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_profile-v2.0.0rc7.aar",
          "url": "store_redirect_profile-v2.0.0rc7.aar",
          "size": 4872,
          "sha512": "b76bafba0ba3cdd62e601d368e1ed7b82da9a29daa53c90b4ad3d65de420983ec40b6a8702df8426c07aadc9b2bd99ee7cb9e59998097a1249a1d9ff3fc802fd",
          "sha256": "e2185732ce81e00d30ec05e000951519fcaacf21ae9d0f9476ed6e88b29c7b47",
          "sha1": "8022f1bb8edf03ef5c122bb79c16fcd323d7ed92",
          "md5": "cac3e80414c415b92e3a995b42d3ca9c"
        }
      ]
    }
  ]
}
