{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_release",
    "version": "v2.0.0rc6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v2.0.0rc6.aar",
          "url": "flutter_release-v2.0.0rc6.aar",
          "size": 36013554,
          "sha512": "240e62a21bec9e8065bea8e594c18e92a0ec3c176e0df5ee2b048a5dc077bf9ea5d31b7a015e03126f3982bab947889dc97ee3a4bb38ed3b5035711dab0b7412",
          "sha256": "2d0fb4c0d53b09174385c1038af6c3426a51caa7daf46c140da7587e30253be4",
          "sha1": "d2eba4b05bd3cff9e3cf11898bcc2b45ac5623e4",
          "md5": "6286f1782e197958a1588019cf42f4ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v2.0.0rc6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v2.0.0rc6.aar",
          "url": "flutter_release-v2.0.0rc6.aar",
          "size": 36013554,
          "sha512": "240e62a21bec9e8065bea8e594c18e92a0ec3c176e0df5ee2b048a5dc077bf9ea5d31b7a015e03126f3982bab947889dc97ee3a4bb38ed3b5035711dab0b7412",
          "sha256": "2d0fb4c0d53b09174385c1038af6c3426a51caa7daf46c140da7587e30253be4",
          "sha1": "d2eba4b05bd3cff9e3cf11898bcc2b45ac5623e4",
          "md5": "6286f1782e197958a1588019cf42f4ca"
        }
      ]
    }
  ]
}
