{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_release",
    "version": "2.0.0rc3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-2.0.0rc3.aar",
          "url": "connectivity_plus_release-2.0.0rc3.aar",
          "size": 9116,
          "sha512": "4842363361dfd04885608d68d1ee4f1c859183ff971859e47315ea855126ef81ad6f5753d68f97e38b779ddf1fce454bc38b604cf8a888b0d63f275a73462c8f",
          "sha256": "5079ce15635438315f7ab0db68fa9a08138fef21d073be3004de87ca822638c7",
          "sha1": "e9b3b8293800089264f1d4a988e62e24c8e634fa",
          "md5": "88ecde1ddbdff8ee609e661c3a909d33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-2.0.0rc3.aar",
          "url": "connectivity_plus_release-2.0.0rc3.aar",
          "size": 9116,
          "sha512": "4842363361dfd04885608d68d1ee4f1c859183ff971859e47315ea855126ef81ad6f5753d68f97e38b779ddf1fce454bc38b604cf8a888b0d63f275a73462c8f",
          "sha256": "5079ce15635438315f7ab0db68fa9a08138fef21d073be3004de87ca822638c7",
          "sha1": "e9b3b8293800089264f1d4a988e62e24c8e634fa",
          "md5": "88ecde1ddbdff8ee609e661c3a909d33"
        }
      ]
    }
  ]
}
