{
  "formatVersion": "1.1",
  "component": {
    "group": "com.empactit.empactit_wifi",
    "module": "empactit_wifi_release",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0rc1.aar",
          "url": "empactit_wifi_release-2.2.0rc1.aar",
          "size": 3642,
          "sha512": "16aa87704e165ed613f2b6c4754c61bc6ff23d0013ff6452ac14477e62ee14ac4c2fdb7952b2463796c7272deeae92802d9c258a68625a5ff0d89c7c590700e1",
          "sha256": "f94c6a39f29ed77b48ab4a8e110bf72b23c833dd73d54100a760b8e7c4bdcaf9",
          "sha1": "748d0202c91bbc409367a9cb9e5b51d8b4f3f4ef",
          "md5": "b49ecef2e2c30c870550a02e18c5e1a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "2.2.0rc1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0rc1.aar",
          "url": "empactit_wifi_release-2.2.0rc1.aar",
          "size": 3642,
          "sha512": "16aa87704e165ed613f2b6c4754c61bc6ff23d0013ff6452ac14477e62ee14ac4c2fdb7952b2463796c7272deeae92802d9c258a68625a5ff0d89c7c590700e1",
          "sha256": "f94c6a39f29ed77b48ab4a8e110bf72b23c833dd73d54100a760b8e7c4bdcaf9",
          "sha1": "748d0202c91bbc409367a9cb9e5b51d8b4f3f4ef",
          "md5": "b49ecef2e2c30c870550a02e18c5e1a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0rc1-sources.jar",
          "url": "empactit_wifi_release-2.2.0rc1-sources.jar",
          "size": 2637,
          "sha512": "45f656e4e0fdf666b791c4e3a93e8a7376109a3630cd2fa1dbdd65fcc58b7926e09226e58e0e32e63b30ea3ebcdb0165a8a599434c7ee10d68185ffc66486c44",
          "sha256": "3b15e813eb358217d03c2b029e24572aba80138c8c54a4ed858a2e963b72b0f9",
          "sha1": "5f5321a4f78b12be6c775449dfde70ec7c17c3cc",
          "md5": "2c9848eae5dad965b0a7fe0ff44411fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0rc1-javadoc.jar",
          "url": "empactit_wifi_release-2.2.0rc1-javadoc.jar",
          "size": 263930,
          "sha512": "2d6ff2a781cce5c6e3b271db4d761cf0c9e0c857f1a2b39f92fe68a27f3e1fe74202fefa1d782de1ce26f61417c1d75d67c4636bbc5f3ed6ad3514d7f8ac99b3",
          "sha256": "131fa5b1ec1bd23696f56b2b7a81ef69d5c93e091453b430b5bee7b8f2522e73",
          "sha1": "7fefebd98c03288af9519b3c2d3b6b6958156370",
          "md5": "7a27939172a3ecbe7dfa45b3d4f452e5"
        }
      ]
    }
  ]
}
