{
  "formatVersion": "1.1",
  "component": {
    "group": "com.alternadom.wifiiot",
    "module": "wifi_iot_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_release-1.0.aar",
          "url": "wifi_iot_release-1.0.aar",
          "size": 38803,
          "sha512": "702823e8d25438611d4687e67375513de6a79b783f6c6a423b8e4186e2e5eccd0d0e674c95bc0a649419b6c466a6ccea4002d6819ecef473719697fc998d2736",
          "sha256": "00c5a9f586d6dcf3d1080726c3a56a8b77c5f45b51d9a9ba764d7c8bf7f5bca0",
          "sha1": "3c9422e019545675ff8642ba8a4402c3476d5770",
          "md5": "1053a9c98528d7b51ff9eee052ebdc39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_release-1.0.aar",
          "url": "wifi_iot_release-1.0.aar",
          "size": 38803,
          "sha512": "702823e8d25438611d4687e67375513de6a79b783f6c6a423b8e4186e2e5eccd0d0e674c95bc0a649419b6c466a6ccea4002d6819ecef473719697fc998d2736",
          "sha256": "00c5a9f586d6dcf3d1080726c3a56a8b77c5f45b51d9a9ba764d7c8bf7f5bca0",
          "sha1": "3c9422e019545675ff8642ba8a4402c3476d5770",
          "md5": "1053a9c98528d7b51ff9eee052ebdc39"
        }
      ]
    }
  ]
}
