{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_profile",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-2.2.0rc1.aar",
          "url": "camera_android_profile-2.2.0rc1.aar",
          "size": 173269,
          "sha512": "230ee3f4ebce84893198defadf72d60045130d9a141522310e875c8370a056f67aa76a22b699ea5419b7a21dfc470496e60839fd7c964e667b309632d97731e5",
          "sha256": "65f04a00314c4e1da7d65176a19dfb246198ce0f87499f1b7bdd20007567df98",
          "sha1": "882625cca71b05ecf157eeebc388f792c62f0cbd",
          "md5": "9778cddc4faedb537c43304cc629709b"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "2.2.0rc1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-2.2.0rc1.aar",
          "url": "camera_android_profile-2.2.0rc1.aar",
          "size": 173269,
          "sha512": "230ee3f4ebce84893198defadf72d60045130d9a141522310e875c8370a056f67aa76a22b699ea5419b7a21dfc470496e60839fd7c964e667b309632d97731e5",
          "sha256": "65f04a00314c4e1da7d65176a19dfb246198ce0f87499f1b7bdd20007567df98",
          "sha1": "882625cca71b05ecf157eeebc388f792c62f0cbd",
          "md5": "9778cddc4faedb537c43304cc629709b"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_profile-2.2.0rc1-sources.jar",
          "url": "camera_android_profile-2.2.0rc1-sources.jar",
          "size": 88560,
          "sha512": "7412fa7f97bec770fd4cb7a13db0146e1e5a8068ce186d93f16fcc531adfd497b9e2485e807c4024f814af55c6f762d9fec3d0e88af9d091fa90075b36d7808c",
          "sha256": "4b547b60686e5eb5af753ed0fc7bd8937f4a16e1779cea4f0a67736e611bc663",
          "sha1": "23117599e141b796a28600d4b48b4a029a5da2c1",
          "md5": "602ff233c226384497d1d2f9c43a4454"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_profile-2.2.0rc1-javadoc.jar",
          "url": "camera_android_profile-2.2.0rc1-javadoc.jar",
          "size": 610876,
          "sha512": "2e79ffbbc0fa7a14105123052625abcd05c2c5a09b77f992eeb26bc6c43329bc18bec6d7a9fa7ad8e9e11d0565a7ede0b3e098d6b3d243c5be2aa5025b5e2ce7",
          "sha256": "57cdc713f289a7213d46d6d1efa319c07ac5e69d96bfa83ec781a85afd4c3500",
          "sha1": "cf3058fa261fad480e0a05dabe156ca987af3880",
          "md5": "7624bb5034c6d9fb6086d6ddc6b3d1f3"
        }
      ]
    }
  ]
}
