{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-2.2.3.aar",
          "url": "shared_preferences_android_profile-2.2.3.aar",
          "size": 12767,
          "sha512": "0bbd876374de6ae9da8181fbea1afd10b43f9483b969b9af537284acdbaa86afa493193b13b9eed233b793173f65c2f65b0c9d9e6e5b632e72edf381bb031428",
          "sha256": "715555d88cee426720270fd63228d6118a5bbb7b95e35305573987ed8ff48f30",
          "sha1": "6b1a89f820fee7174bc4679cc1fad6df49826e67",
          "md5": "a22a8d56c16c56a6cc4cac6b17dfc5e0"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-2.2.3.aar",
          "url": "shared_preferences_android_profile-2.2.3.aar",
          "size": 12767,
          "sha512": "0bbd876374de6ae9da8181fbea1afd10b43f9483b969b9af537284acdbaa86afa493193b13b9eed233b793173f65c2f65b0c9d9e6e5b632e72edf381bb031428",
          "sha256": "715555d88cee426720270fd63228d6118a5bbb7b95e35305573987ed8ff48f30",
          "sha1": "6b1a89f820fee7174bc4679cc1fad6df49826e67",
          "md5": "a22a8d56c16c56a6cc4cac6b17dfc5e0"
        }
      ]
    }
  ]
}
