{
  "formatVersion": "1.1",
  "component": {
    "group": "com.danieldallos.storeredirect",
    "module": "store_redirect_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_debug-v1.0.0.aar",
          "url": "store_redirect_debug-v1.0.0.aar",
          "size": 5060,
          "sha512": "f0cf145dc3bee8db33b19720013999564ab7cb109ba53ad84bca52dcc10905b3851e58c1e913f1c5bb69a954f352498c758db6e62188a4b0f72c33cff8a18a29",
          "sha256": "28e927530d7985195b4775272ee167373ed46cedf897b6936f3d5b17d8759aea",
          "sha1": "a1d8d0a10ee57d725f7622d14a49535d845e1cea",
          "md5": "0bb9bbde04e0902214bb09c014e2f584"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_debug-v1.0.0.aar",
          "url": "store_redirect_debug-v1.0.0.aar",
          "size": 5060,
          "sha512": "f0cf145dc3bee8db33b19720013999564ab7cb109ba53ad84bca52dcc10905b3851e58c1e913f1c5bb69a954f352498c758db6e62188a4b0f72c33cff8a18a29",
          "sha256": "28e927530d7985195b4775272ee167373ed46cedf897b6936f3d5b17d8759aea",
          "sha1": "a1d8d0a10ee57d725f7622d14a49535d845e1cea",
          "md5": "0bb9bbde04e0902214bb09c014e2f584"
        }
      ]
    }
  ]
}
