{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-2.0.1.aar",
          "url": "permission_handler_android_debug-2.0.1.aar",
          "size": 26382,
          "sha512": "a05135d6b730b1461463bef56dbad7670640df3b27fdec7414a69972612fb1cd9e935a9037cdfdf3bfb8706318874376df9ad815917ef07878a97ee268dc3f87",
          "sha256": "1829a62e690fe35dbe0add9e2d18b94d13d4858abfdaca6449479893353b96c9",
          "sha1": "586460f8fbfc7500aedd85eb1067fe613e03e60e",
          "md5": "e9fcdbddceeff1996991a87c73461d7e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-2.0.1.aar",
          "url": "permission_handler_android_debug-2.0.1.aar",
          "size": 26382,
          "sha512": "a05135d6b730b1461463bef56dbad7670640df3b27fdec7414a69972612fb1cd9e935a9037cdfdf3bfb8706318874376df9ad815917ef07878a97ee268dc3f87",
          "sha256": "1829a62e690fe35dbe0add9e2d18b94d13d4858abfdaca6449479893353b96c9",
          "sha1": "586460f8fbfc7500aedd85eb1067fe613e03e60e",
          "md5": "e9fcdbddceeff1996991a87c73461d7e"
        }
      ]
    }
  ]
}
