{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_debug",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-2.5.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-2.5.0.aar",
          "size": 4897,
          "sha512": "b9860359a4ac5fe8da990e310708523cc18867388580df77d5e77188ab151ba51bd61a60ba11ae8284e342961fbd454d1979ab7c733d83b14a0ff1d82523d1d4",
          "sha256": "43adc5399ea6aa8b3a6f8a2b2a5c811df5c069b5fa9677c114aa72e55a15828d",
          "sha1": "57a43b3628897c926959883f3c87c5ea8d683d54",
          "md5": "2172ee3cbc27c3e53e6886bc38d24cf7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-2.5.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-2.5.0.aar",
          "size": 4897,
          "sha512": "b9860359a4ac5fe8da990e310708523cc18867388580df77d5e77188ab151ba51bd61a60ba11ae8284e342961fbd454d1979ab7c733d83b14a0ff1d82523d1d4",
          "sha256": "43adc5399ea6aa8b3a6f8a2b2a5c811df5c069b5fa9677c114aa72e55a15828d",
          "sha1": "57a43b3628897c926959883f3c87c5ea8d683d54",
          "md5": "2172ee3cbc27c3e53e6886bc38d24cf7"
        }
      ]
    }
  ]
}
