{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0rc1.aar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0rc1.aar",
          "size": 2494,
          "sha512": "b48ec869149ee5c7d76c12ef38da88f55fca71496352b27a35ca38215a6767163273d12bb7d454f80df8bd5620da29f7d6e7f16403b812433ab9e058707432d4",
          "sha256": "16fc5aaebb64858cbfaf303aad39e2afa85711c2c36f7244aefe827dfc09cd30",
          "sha1": "df3b2bc4926b4b5454dba58fcb610ce940792468",
          "md5": "598f3e66df391468a15563476ba32d9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0rc1.aar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0rc1.aar",
          "size": 2494,
          "sha512": "b48ec869149ee5c7d76c12ef38da88f55fca71496352b27a35ca38215a6767163273d12bb7d454f80df8bd5620da29f7d6e7f16403b812433ab9e058707432d4",
          "sha256": "16fc5aaebb64858cbfaf303aad39e2afa85711c2c36f7244aefe827dfc09cd30",
          "sha1": "df3b2bc4926b4b5454dba58fcb610ce940792468",
          "md5": "598f3e66df391468a15563476ba32d9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0rc1-sources.jar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0rc1-sources.jar",
          "size": 2659,
          "sha512": "d848b9ac3a80bd88694f7d35de2abc2866f65393d53caa1f49513063e17fe497a4b7e1ed09dc3736f529a166f1491dfb78c703a51f0fe0950082488869f2b352",
          "sha256": "2930f0a83f74dc7a57026b471c4443a3e5cb4f8b5f80bf45d161dd31675194c7",
          "sha1": "82b1c36d1af62197547e6c132ae64f520e3ad7a7",
          "md5": "fb7b3ee0458fe0f3ec0a8116c68f72ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.2.0rc1-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_release-2.2.0rc1-javadoc.jar",
          "size": 269839,
          "sha512": "66c6d66398b3e57c9d887c5b48666eeb7a622e662a8f869fdab9f138cd5e25853eb3a6c4675551c317d9a19824995348207cdd19532a9b4981e1e17c90aefe43",
          "sha256": "ba6acc3fd3c9cb22de266b8ab8ac5ca1fa5b5d5149790d79a32eb03b5f8e5ff1",
          "sha1": "d3156630741519896583476570894b27089b3f61",
          "md5": "6986b3b27d209233ea973c05535170ba"
        }
      ]
    }
  ]
}
