{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.googleapiavailability",
    "module": "google_api_availability_android_release",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0rc1.aar",
          "url": "google_api_availability_android_release-2.2.0rc1.aar",
          "size": 10356,
          "sha512": "4bd29c49ce152f6dc80b3f79521925580db933a40dd530ec11e64eed08b72d93188e70b3c6d4cfe90efcfafe49e882fadbd94a417f457eac99ca0a96502f6704",
          "sha256": "96068b7d874e46e4e82748d699f62d98514b7620b3f3e7310f9e6fea0371d3e5",
          "sha1": "a37df0706cab55505dea5377bd9d87181d5dcdd1",
          "md5": "f33e674092bf0eaa683ebdf8a5ded742"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0rc1.aar",
          "url": "google_api_availability_android_release-2.2.0rc1.aar",
          "size": 10356,
          "sha512": "4bd29c49ce152f6dc80b3f79521925580db933a40dd530ec11e64eed08b72d93188e70b3c6d4cfe90efcfafe49e882fadbd94a417f457eac99ca0a96502f6704",
          "sha256": "96068b7d874e46e4e82748d699f62d98514b7620b3f3e7310f9e6fea0371d3e5",
          "sha1": "a37df0706cab55505dea5377bd9d87181d5dcdd1",
          "md5": "f33e674092bf0eaa683ebdf8a5ded742"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0rc1-sources.jar",
          "url": "google_api_availability_android_release-2.2.0rc1-sources.jar",
          "size": 4340,
          "sha512": "d3df5efb2e69693c10aa20233be11edb72b79729a86317bfd96bb270a3d17bb4f9ba06bc09dd1338b01f6b8132bbb44ddbc7ad867358fd1e0fa91a46ed20497b",
          "sha256": "1d2da8bcf52c79efecd43e2d2306565c1aa43a95c279c04324fb6aa8012eafd9",
          "sha1": "4396701311008b7311eabe67030bba81fbe42c2a",
          "md5": "82113b662a4e791d8bf1804d60a14de5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0rc1-javadoc.jar",
          "url": "google_api_availability_android_release-2.2.0rc1-javadoc.jar",
          "size": 269338,
          "sha512": "5dfd3d2be5a95cef0ce353394505aabfbbce11ddab524fee43c759f988de3aa9126a56c30c35d99c7f1998f5440821fe663b699bf03d1651b29cd973bbb42691",
          "sha256": "4416d1e80d44a9ea672c90aa884923b99e9cbb70443bfb017ba12dbcc5affedf",
          "sha1": "1dbced460f566033149b609476519eaaae1c1beb",
          "md5": "a4010b0c3437d7f9725199e256ba7a8d"
        }
      ]
    }
  ]
}
