{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-2.2.0rc1.aar",
          "url": "url_launcher_android_release-2.2.0rc1.aar",
          "size": 29359,
          "sha512": "3aeb20f0a9b1dee464f2791fb1a4b9f615da421fc113f95ea1adcd06a0a2a8a837d4e58e2d09f836e4ef3ea6727960dbea2c12d672c571bec7b93858ab7ceda6",
          "sha256": "fe633ef68bbf4567cdf4988d2014440aa977e948c0353fd6b07fe1e70a73c49e",
          "sha1": "482abc89361c59255cb8a75fcc0acdd67103435b",
          "md5": "d5aba68b019df68546084ed576eb5a64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-2.2.0rc1.aar",
          "url": "url_launcher_android_release-2.2.0rc1.aar",
          "size": 29359,
          "sha512": "3aeb20f0a9b1dee464f2791fb1a4b9f615da421fc113f95ea1adcd06a0a2a8a837d4e58e2d09f836e4ef3ea6727960dbea2c12d672c571bec7b93858ab7ceda6",
          "sha256": "fe633ef68bbf4567cdf4988d2014440aa977e948c0353fd6b07fe1e70a73c49e",
          "sha1": "482abc89361c59255cb8a75fcc0acdd67103435b",
          "md5": "d5aba68b019df68546084ed576eb5a64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-2.2.0rc1-sources.jar",
          "url": "url_launcher_android_release-2.2.0rc1-sources.jar",
          "size": 9302,
          "sha512": "886ed44cccd21b6a1adf167e5256ba7c7906c951a8723078c2072f6d1962af6397bbc87bb7f9b9889f75553f1ebbbb5db7600667e075f931cbd1d87a09beac20",
          "sha256": "b020d282f9a22c90b2239b136bf74070d12066db0ac939944a3c436814d183db",
          "sha1": "2c6302b792dbdffaba43743e5057e5869b5d0b97",
          "md5": "66ff5ff6f80f555357b9e72f09baa634"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-2.2.0rc1-javadoc.jar",
          "url": "url_launcher_android_release-2.2.0rc1-javadoc.jar",
          "size": 333450,
          "sha512": "81eff4c09d743ea10ec70e6715ea2647778735261b542a58fc655250a99d06d8c2aa36ea635ebf73ef046830d066dbd4f5ca1a88e364aad33315f6a776722004",
          "sha256": "5bc4e53b0697d0c4c275c25aa8797e2b549ae78995b38c20d189fb56009c81be",
          "sha1": "30bf1cc97f3a7d8d5b665ec94a5a91130de3ee8e",
          "md5": "9b06ebd6de157e4ca8a442c682f92edc"
        }
      ]
    }
  ]
}
