{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_release",
    "version": "v2.0.0rc7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v2.0.0rc7.aar",
          "url": "flutter_release-v2.0.0rc7.aar",
          "size": 36015910,
          "sha512": "5eee4fdd877e875197a500ee801aed4a2ba492dec1eef10b61f13d72b1d1a6286753e9172f9a96a62e13aedcaf39569ad40314276c79d1751eb54974252f78ec",
          "sha256": "99bd89449eebe2958517a5f505699dc8df52dc659de09678602804658035fca7",
          "sha1": "dc9220b024791203a3295a5b2bc2c256db41eb3a",
          "md5": "598fb0c0a36d1e7af419ae7e6719d505"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v2.0.0rc7"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v2.0.0rc7.aar",
          "url": "flutter_release-v2.0.0rc7.aar",
          "size": 36015910,
          "sha512": "5eee4fdd877e875197a500ee801aed4a2ba492dec1eef10b61f13d72b1d1a6286753e9172f9a96a62e13aedcaf39569ad40314276c79d1751eb54974252f78ec",
          "sha256": "99bd89449eebe2958517a5f505699dc8df52dc659de09678602804658035fca7",
          "sha1": "dc9220b024791203a3295a5b2bc2c256db41eb3a",
          "md5": "598fb0c0a36d1e7af419ae7e6719d505"
        }
      ]
    }
  ]
}
