{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_debug",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-2.2.0rc1.aar",
          "url": "camera_android_debug-2.2.0rc1.aar",
          "size": 173528,
          "sha512": "d8b09469a5bb57f446f054b992ac1a5385f0ac4ec561589a1fb87eac3d59d94b3239b8e14bd0bca35f89ed3dd5e98d71feb497a9ba01191aadb09e0655d9227b",
          "sha256": "815d71d5f5c44c4d264d6e5795efc83f861b21258e00976908141d73d67d483b",
          "sha1": "cc0fe43c5ccb62cbfacbf8424b1f195f1fdde5a5",
          "md5": "03889a41b36b4879b4375c7e70e0d4eb"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "2.2.0rc1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-2.2.0rc1.aar",
          "url": "camera_android_debug-2.2.0rc1.aar",
          "size": 173528,
          "sha512": "d8b09469a5bb57f446f054b992ac1a5385f0ac4ec561589a1fb87eac3d59d94b3239b8e14bd0bca35f89ed3dd5e98d71feb497a9ba01191aadb09e0655d9227b",
          "sha256": "815d71d5f5c44c4d264d6e5795efc83f861b21258e00976908141d73d67d483b",
          "sha1": "cc0fe43c5ccb62cbfacbf8424b1f195f1fdde5a5",
          "md5": "03889a41b36b4879b4375c7e70e0d4eb"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_debug-2.2.0rc1-sources.jar",
          "url": "camera_android_debug-2.2.0rc1-sources.jar",
          "size": 88559,
          "sha512": "b5fc6309cd2849f0becd634bd8152ab7d4d13a408b0bfde1043fa64c01a62d58b1f1469cb9957902483ce40ce3cb93e041e7d34b28e5c9b4625ed2a704f74f3b",
          "sha256": "a5e82bc0082af09cfdb4c887dfc115da0610fe56b667556dcef20c7aa87a869a",
          "sha1": "d9093448587aaf1d25f6fc317bd5659af46bb4b9",
          "md5": "fd06792af1ced912093135c22eb4a62f"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_debug-2.2.0rc1-javadoc.jar",
          "url": "camera_android_debug-2.2.0rc1-javadoc.jar",
          "size": 610868,
          "sha512": "182c6a07ea3b7771ad402dbfbf806e63e0e0dac07e504a4cd026182995b26c340a72b9fa9f381a15de219c7003d1b6a45a1667dcb306d3c8d4b63b0f441a0a76",
          "sha256": "c4fdbf8a522ef2db834512ea0f0725f84a7a65798388d423dde4d3dfae8cb62b",
          "sha1": "20ccc1848ed3e437fee7a88d99d142eb7aee8682",
          "md5": "769b7b3837886bff365683188bc4a2f1"
        }
      ]
    }
  ]
}
