{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "v1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-v1.1.3.aar",
          "url": "device_info_plus_profile-v1.1.3.aar",
          "size": 9519,
          "sha512": "109e531a114e3d8bdb6b16d2fef0ecbd7fb8cf06aa2938f2edc3307d86b7822a7cf2cdfce6272a01e3529375cd510901e0d8796387fb410453d9cce26211b88a",
          "sha256": "777dfe7d752bec0968942a502493f386a524fa1bc8cfc859a4b6925a3a786101",
          "sha1": "7f5097111762dd1251db6c3bd8c748875187d5cb",
          "md5": "754f33fb47f1a5b8f8e93011bcc3bc88"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-v1.1.3.aar",
          "url": "device_info_plus_profile-v1.1.3.aar",
          "size": 9519,
          "sha512": "109e531a114e3d8bdb6b16d2fef0ecbd7fb8cf06aa2938f2edc3307d86b7822a7cf2cdfce6272a01e3529375cd510901e0d8796387fb410453d9cce26211b88a",
          "sha256": "777dfe7d752bec0968942a502493f386a524fa1bc8cfc859a4b6925a3a786101",
          "sha1": "7f5097111762dd1251db6c3bd8c748875187d5cb",
          "md5": "754f33fb47f1a5b8f8e93011bcc3bc88"
        }
      ]
    }
  ]
}
