{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flutternetwork.wifi.wifi_scan",
    "module": "wifi_scan_debug",
    "version": "v1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_debug-v1.1.0.aar",
          "url": "wifi_scan_debug-v1.1.0.aar",
          "size": 19960,
          "sha512": "3644ee370677d97dca98ceff4ed965cdca1d0744f6931f544b108e4059ff56dc3f152a38e4a370d382fd4c70b889c61a7c5e6568a17448dd8ec842699728d757",
          "sha256": "dbe3d82f70e70ccf669dc01ccb487beb76662c55d6bc0a38762ec6e8395549b8",
          "sha1": "24082639778b216a5b5497e6b0aa3a1c2c819e32",
          "md5": "03652cbca5b4d12bbbe0c1e2e8519ce2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_debug-v1.1.0.aar",
          "url": "wifi_scan_debug-v1.1.0.aar",
          "size": 19960,
          "sha512": "3644ee370677d97dca98ceff4ed965cdca1d0744f6931f544b108e4059ff56dc3f152a38e4a370d382fd4c70b889c61a7c5e6568a17448dd8ec842699728d757",
          "sha256": "dbe3d82f70e70ccf669dc01ccb487beb76662c55d6bc0a38762ec6e8395549b8",
          "sha1": "24082639778b216a5b5497e6b0aa3a1c2c819e32",
          "md5": "03652cbca5b4d12bbbe0c1e2e8519ce2"
        }
      ]
    }
  ]
}
