{
  "formatVersion": "1.1",
  "component": {
    "group": "com.alternadom.wifiiot",
    "module": "wifi_iot_release",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_release-2.2.0rc1.aar",
          "url": "wifi_iot_release-2.2.0rc1.aar",
          "size": 36496,
          "sha512": "5bc975a83e7296fcdae620519ac8bd119d9371655ef2f4ccac4bc6c19c2e8fd26ff520a749d25113bf175941dd441d8c389ce1911c9479c255705ba30bed50ab",
          "sha256": "c1c8d440f1d75ed1323fdf14eeb87bfc725c94f3e6e279b6e5d336df557ca44c",
          "sha1": "43e8904f25a6df053501ea3b6280111305a61fd4",
          "md5": "691e1292ec01c6a243cb3ebff7159409"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_release-2.2.0rc1.aar",
          "url": "wifi_iot_release-2.2.0rc1.aar",
          "size": 36496,
          "sha512": "5bc975a83e7296fcdae620519ac8bd119d9371655ef2f4ccac4bc6c19c2e8fd26ff520a749d25113bf175941dd441d8c389ce1911c9479c255705ba30bed50ab",
          "sha256": "c1c8d440f1d75ed1323fdf14eeb87bfc725c94f3e6e279b6e5d336df557ca44c",
          "sha1": "43e8904f25a6df053501ea3b6280111305a61fd4",
          "md5": "691e1292ec01c6a243cb3ebff7159409"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wifi_iot_release-2.2.0rc1-sources.jar",
          "url": "wifi_iot_release-2.2.0rc1-sources.jar",
          "size": 16672,
          "sha512": "737aedd0f7121d8fe389565cc638560e0084121601c49d510567d665a07c111cf8f5487418637e4b134f85a7ef5a4b7eae4feb4fb539abf6e10109a409d0c77b",
          "sha256": "78d20afced54211d84ee34759b0a087ee53ef4b15ba7cbbe1c102b0bbe26404f",
          "sha1": "78e31d8e41c163bfa7c43f000e81446fd604047e",
          "md5": "de162ae32675181e0481cebac91c6152"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wifi_iot_release-2.2.0rc1-javadoc.jar",
          "url": "wifi_iot_release-2.2.0rc1-javadoc.jar",
          "size": 288067,
          "sha512": "b3e376113733b208162be628f774f46d476c3d9255cd33cd9ade00a8b8e08ceb2ff1d864a560ff895f2423edc46cb32675a56f29087800bfdcf60919f9872224",
          "sha256": "a3d7e9e0bab0be699d284fa537eba7f387fa87c8a69e1ff071daeec144729d71",
          "sha1": "a9a6ec58da3336bc6c70633598df65259f401b22",
          "md5": "7bf7d44d98541af83f71a76719637312"
        }
      ]
    }
  ]
}
