{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.googleapiavailability",
    "module": "google_api_availability_android_release",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0.aar",
          "url": "google_api_availability_android_release-2.2.0.aar",
          "size": 10356,
          "sha512": "4bd29c49ce152f6dc80b3f79521925580db933a40dd530ec11e64eed08b72d93188e70b3c6d4cfe90efcfafe49e882fadbd94a417f457eac99ca0a96502f6704",
          "sha256": "96068b7d874e46e4e82748d699f62d98514b7620b3f3e7310f9e6fea0371d3e5",
          "sha1": "a37df0706cab55505dea5377bd9d87181d5dcdd1",
          "md5": "f33e674092bf0eaa683ebdf8a5ded742"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0.aar",
          "url": "google_api_availability_android_release-2.2.0.aar",
          "size": 10356,
          "sha512": "4bd29c49ce152f6dc80b3f79521925580db933a40dd530ec11e64eed08b72d93188e70b3c6d4cfe90efcfafe49e882fadbd94a417f457eac99ca0a96502f6704",
          "sha256": "96068b7d874e46e4e82748d699f62d98514b7620b3f3e7310f9e6fea0371d3e5",
          "sha1": "a37df0706cab55505dea5377bd9d87181d5dcdd1",
          "md5": "f33e674092bf0eaa683ebdf8a5ded742"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0-sources.jar",
          "url": "google_api_availability_android_release-2.2.0-sources.jar",
          "size": 4340,
          "sha512": "d3df5efb2e69693c10aa20233be11edb72b79729a86317bfd96bb270a3d17bb4f9ba06bc09dd1338b01f6b8132bbb44ddbc7ad867358fd1e0fa91a46ed20497b",
          "sha256": "1d2da8bcf52c79efecd43e2d2306565c1aa43a95c279c04324fb6aa8012eafd9",
          "sha1": "4396701311008b7311eabe67030bba81fbe42c2a",
          "md5": "82113b662a4e791d8bf1804d60a14de5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_api_availability_android_release-2.2.0-javadoc.jar",
          "url": "google_api_availability_android_release-2.2.0-javadoc.jar",
          "size": 269326,
          "sha512": "144eac208ad9f9bd2fe91c1b6388eb4ff4302695af420c1b5f403c1afb2e9f7407b68a5bab7e10b4363fc506887b1dc374f888ec30f60c5d0bf05f771b1f8d5d",
          "sha256": "93ae4acec94e9f1bd328827a41d179bac165b156165e3f00218c53465bdfa0c3",
          "sha1": "59e100df17b9728c258cc953e003749727f92b76",
          "md5": "0089db4187d0936e913f9445ca32eee4"
        }
      ]
    }
  ]
}
