{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-2.0.0.aar",
          "url": "device_info_plus_release-2.0.0.aar",
          "size": 9526,
          "sha512": "f19438a320da08cc390de924998ccb4ddb2442deee00a869dbd4a723b0534ccaf7b7e882ac9c8fa2f1a73c588ba8483e6f55715e267ce7025edf50f12e8e4078",
          "sha256": "5a7c205b52e80612a573c3c809464d2bf60b42a4742e84284982d2a4172b634b",
          "sha1": "b5e33855f07629a977a42a07ed569eca50b76703",
          "md5": "2d2e8fc5bfe3ef3476db79cabb9d9ff6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-2.0.0.aar",
          "url": "device_info_plus_release-2.0.0.aar",
          "size": 9526,
          "sha512": "f19438a320da08cc390de924998ccb4ddb2442deee00a869dbd4a723b0534ccaf7b7e882ac9c8fa2f1a73c588ba8483e6f55715e267ce7025edf50f12e8e4078",
          "sha256": "5a7c205b52e80612a573c3c809464d2bf60b42a4742e84284982d2a4172b634b",
          "sha1": "b5e33855f07629a977a42a07ed569eca50b76703",
          "md5": "2d2e8fc5bfe3ef3476db79cabb9d9ff6"
        }
      ]
    }
  ]
}
