{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-2.0.0.aar",
          "url": "device_info_plus_release-2.0.0.aar",
          "size": 9666,
          "sha512": "73843f5c5729ca351efddd024a7ecb626ffdae585c1ff7477f4807e772c18e2676489820d49c128a7ab8235535a4633810cfd1c07545b8ef05b03f37647c2626",
          "sha256": "a82c5883d0734425e06b47ed7ffa4ac3375b3d52788ae358da9174eb6b3a7306",
          "sha1": "c7bc876eae05fe4f1786719ee7102b830d5e4f5a",
          "md5": "4370204e82cd8d3cce344f437833a7d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-2.0.0.aar",
          "url": "device_info_plus_release-2.0.0.aar",
          "size": 9666,
          "sha512": "73843f5c5729ca351efddd024a7ecb626ffdae585c1ff7477f4807e772c18e2676489820d49c128a7ab8235535a4633810cfd1c07545b8ef05b03f37647c2626",
          "sha256": "a82c5883d0734425e06b47ed7ffa4ac3375b3d52788ae358da9174eb6b3a7306",
          "sha1": "c7bc876eae05fe4f1786719ee7102b830d5e4f5a",
          "md5": "4370204e82cd8d3cce344f437833a7d4"
        }
      ]
    }
  ]
}
