{
  "formatVersion": "1.1",
  "component": {
    "group": "net.touchcapture.qr.flutterqr",
    "module": "qr_code_scanner_profile",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-2.0.0.aar",
          "url": "qr_code_scanner_profile-2.0.0.aar",
          "size": 37529,
          "sha512": "13cdab1238c6dc540965f6ddf63b71ed880c725101897eeae1fafc91750e9c408128552a6104652c5366761a56796f14efbdb0d86c4f8168ecd9e5da9775a04f",
          "sha256": "6138ce681d38d025ccfb0d94c5a37d56ea7b6df12a16766c2bf10fb41e4176b6",
          "sha1": "e2ddf02ecd8e72b30ae364716da9ae88ae2329fd",
          "md5": "a7be83f69a3580c49c57e54ee585a130"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-2.0.0.aar",
          "url": "qr_code_scanner_profile-2.0.0.aar",
          "size": 37529,
          "sha512": "13cdab1238c6dc540965f6ddf63b71ed880c725101897eeae1fafc91750e9c408128552a6104652c5366761a56796f14efbdb0d86c4f8168ecd9e5da9775a04f",
          "sha256": "6138ce681d38d025ccfb0d94c5a37d56ea7b6df12a16766c2bf10fb41e4176b6",
          "sha1": "e2ddf02ecd8e72b30ae364716da9ae88ae2329fd",
          "md5": "a7be83f69a3580c49c57e54ee585a130"
        }
      ]
    }
  ]
}
