{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-2.2.0rc1.aar",
          "url": "webview_flutter_android_release-2.2.0rc1.aar",
          "size": 267282,
          "sha512": "d52c0ff1aeb72d2fda0ad94130fa3c9cff6219db0041e16ad9b9ecb259b2614906e84e4915cbe86c69a6a9d561659da35f3730e549a43e77d4a194fbc4bf3ecb",
          "sha256": "5466a945d2b50be85a0b4d7898c7ab8efe8fe5009185c79db0a0988dca062f4b",
          "sha1": "e7038010bbf8224b4001490063aaf91d987341e2",
          "md5": "c075c851a8c0badd76d66c27bde7ceb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-2.2.0rc1.aar",
          "url": "webview_flutter_android_release-2.2.0rc1.aar",
          "size": 267282,
          "sha512": "d52c0ff1aeb72d2fda0ad94130fa3c9cff6219db0041e16ad9b9ecb259b2614906e84e4915cbe86c69a6a9d561659da35f3730e549a43e77d4a194fbc4bf3ecb",
          "sha256": "5466a945d2b50be85a0b4d7898c7ab8efe8fe5009185c79db0a0988dca062f4b",
          "sha1": "e7038010bbf8224b4001490063aaf91d987341e2",
          "md5": "c075c851a8c0badd76d66c27bde7ceb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-2.2.0rc1-sources.jar",
          "url": "webview_flutter_android_release-2.2.0rc1-sources.jar",
          "size": 61672,
          "sha512": "986c5aa1d166cef12d3d4eaaf652636388c1b06d993169f83810790eb66bc579833fb64df4b88335176df2341bfdfdf6dbce69fb41e9da565c9ee067c5085918",
          "sha256": "3a0ce9de3c1fe73164306fa437316145e9eb13ee478c7d2171ce7051750abf53",
          "sha1": "a0ad416109d6d45590d981ecf289e204bd033295",
          "md5": "526a7c1af86e378623197367f4cfbcb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-2.2.0rc1-javadoc.jar",
          "url": "webview_flutter_android_release-2.2.0rc1-javadoc.jar",
          "size": 751641,
          "sha512": "811ac355b6938fdd0e28df66b9d8d07f7dab5a8a65493ba8230b8bbb585ccfa4b5c3130fa9ecf0aa2b2bcbadb23f4a1819d8a0f4be4a2f9a0a6c498a9d03b67c",
          "sha256": "4d4c3f18b83b51ef96f5d8c470ec3edde16e7c3d3e26965a231b350fe1cd8cfd",
          "sha1": "a077104f5bbbb0b4468b0f5f779526727df43a80",
          "md5": "1fe4471c414ba6a963ef4de5c34beb56"
        }
      ]
    }
  ]
}
