{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-2.1.4.aar",
          "url": "webview_flutter_android_profile-2.1.4.aar",
          "size": 106268,
          "sha512": "1f4f132ab7a49a05bece86abc25f095b8607a8c77bc8fdaeef5b447ab10b275fb4e3743f3cf27a5ad3e6cbe65c3ec57e85fa41c18b07b9b8d541975e30f936b7",
          "sha256": "4795d5e855bc489d41399b3da0632704c20e33384773b473b61d3c91c557e199",
          "sha1": "80c2560ca4c0bb6c7028ad66dab3c825c92a1129",
          "md5": "fc07341df7fff39c3497c29d77acaaae"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-2.1.4.aar",
          "url": "webview_flutter_android_profile-2.1.4.aar",
          "size": 106268,
          "sha512": "1f4f132ab7a49a05bece86abc25f095b8607a8c77bc8fdaeef5b447ab10b275fb4e3743f3cf27a5ad3e6cbe65c3ec57e85fa41c18b07b9b8d541975e30f936b7",
          "sha256": "4795d5e855bc489d41399b3da0632704c20e33384773b473b61d3c91c557e199",
          "sha1": "80c2560ca4c0bb6c7028ad66dab3c825c92a1129",
          "md5": "fc07341df7fff39c3497c29d77acaaae"
        }
      ]
    }
  ]
}
