{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13191,
          "sha512": "2cd45f2e57ed587adc9e94244a7068a4e78e033e4841371f2d12577e03b71f5acd6c2aef7802667fbba4fdefa1fa44428352e48d136ea8fd92148c9807675e02",
          "sha256": "5ff7dda8d0794717442c3d5cfe1e64d2fe4408a9dba54ff9beea6381df4135b0",
          "sha1": "8b3e962729158eaa7ca377954aa34acccb7d3b87",
          "md5": "9b3c72907ac345cc2ebcfb7fa0ff099c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13191,
          "sha512": "2cd45f2e57ed587adc9e94244a7068a4e78e033e4841371f2d12577e03b71f5acd6c2aef7802667fbba4fdefa1fa44428352e48d136ea8fd92148c9807675e02",
          "sha256": "5ff7dda8d0794717442c3d5cfe1e64d2fe4408a9dba54ff9beea6381df4135b0",
          "sha1": "8b3e962729158eaa7ca377954aa34acccb7d3b87",
          "md5": "9b3c72907ac345cc2ebcfb7fa0ff099c"
        }
      ]
    }
  ]
}
