{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pay_android",
    "module": "pay_android_profile",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_profile-2.2.0rc1.aar",
          "url": "pay_android_profile-2.2.0rc1.aar",
          "size": 23644,
          "sha512": "1fc36ab437e3ace3fe01422e3e646caaedea6430bb5d154fe89213a00c156367f72f876cfd938c68dce26535c34e3edd09fd26db9ae97eb9dc1883ad9596f0c9",
          "sha256": "7f4ea3a70e1bf479ff14b2817bb5c7748dde5d6203feb5676d43f592806078b0",
          "sha1": "53906525e97a26e9b606b56ffb3e7b955935b2dd",
          "md5": "b9193ee0a642a0e333e49f90d578849c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_profile-2.2.0rc1.aar",
          "url": "pay_android_profile-2.2.0rc1.aar",
          "size": 23644,
          "sha512": "1fc36ab437e3ace3fe01422e3e646caaedea6430bb5d154fe89213a00c156367f72f876cfd938c68dce26535c34e3edd09fd26db9ae97eb9dc1883ad9596f0c9",
          "sha256": "7f4ea3a70e1bf479ff14b2817bb5c7748dde5d6203feb5676d43f592806078b0",
          "sha1": "53906525e97a26e9b606b56ffb3e7b955935b2dd",
          "md5": "b9193ee0a642a0e333e49f90d578849c"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_profile-2.2.0rc1-sources.jar",
          "url": "pay_android_profile-2.2.0rc1-sources.jar",
          "size": 10545,
          "sha512": "9d221a27d20dfec7d3231a4e60e1a52ddaeb2da9a17857ceeefcea17a688d17fb7da85acf447bf7316e68ab5b78242fd42de5a63a56e62fca6a1f57c9742a212",
          "sha256": "a44f1227c059eb244c6dd77dadc853258f99a65a992761c3ec7ab714a42e09db",
          "sha1": "46924b9a413b27324d4be1c478d959a7a3f15490",
          "md5": "079d17719b0832269738a4ae2ab18108"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_profile-2.2.0rc1-javadoc.jar",
          "url": "pay_android_profile-2.2.0rc1-javadoc.jar",
          "size": 307787,
          "sha512": "c29ee17995fb42c4471679b9aeaa5984e9d100b4a3a7eea151b97a7646fe01e75a19c912c114fe8c62ec7a0211aa3ba7730e6f61640c9a33fe7229b731afac41",
          "sha256": "736d289c7128bdccddf94b7d9f8a5894f2e51c95232e99781b149376502cade5",
          "sha1": "9dc14adb70ac39d88836632b9db6e3a64058e4cf",
          "md5": "9214d7aba1731ba3fd7a8210f7f20c10"
        }
      ]
    }
  ]
}
