{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-2.0.0.aar",
          "url": "device_info_plus_profile-2.0.0.aar",
          "size": 9670,
          "sha512": "8c9001cf0d256888074ee1bf586e0f320a77c9cecee6ff52d31fe60d2d314fae0055ee57aaf9a394f23c2796d58285067dce62c76c29ee0c026007108cf652b6",
          "sha256": "1957164d1a725f6defa9000a277575ff022c8309d14f5630e8cac82bd8853373",
          "sha1": "a1ce7174e3a9b69a3f7b74cc249f986ec206ddb0",
          "md5": "d24b23149a9eaa926d44a53d52e74cd3"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-2.0.0.aar",
          "url": "device_info_plus_profile-2.0.0.aar",
          "size": 9670,
          "sha512": "8c9001cf0d256888074ee1bf586e0f320a77c9cecee6ff52d31fe60d2d314fae0055ee57aaf9a394f23c2796d58285067dce62c76c29ee0c026007108cf652b6",
          "sha256": "1957164d1a725f6defa9000a277575ff022c8309d14f5630e8cac82bd8853373",
          "sha1": "a1ce7174e3a9b69a3f7b74cc249f986ec206ddb0",
          "md5": "d24b23149a9eaa926d44a53d52e74cd3"
        }
      ]
    }
  ]
}
