{
  "formatVersion": "1.1",
  "component": {
    "group": "com.empactit.empactit_wifi",
    "module": "empactit_wifi_release",
    "version": "v2.0.2test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-v2.0.2test.aar",
          "url": "empactit_wifi_release-v2.0.2test.aar",
          "size": 5775,
          "sha512": "aa10db865edc756c68f9955e92ca7b193fc6142d9ba007bb55e58eaa890d341357decede8da21c86da18033337eb43e262e79cc5378dda46212037f7a6d4bb72",
          "sha256": "7afab991cc2aeea0ad76a49cc86706b03e5e2bcafa390ac3c6d3beca55c06d71",
          "sha1": "f0051b89a897c45ee2f761e9976c78fd3de9ba98",
          "md5": "601b913f06cf1f4988f8e62af68787ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v2.0.2test"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-v2.0.2test.aar",
          "url": "empactit_wifi_release-v2.0.2test.aar",
          "size": 5775,
          "sha512": "aa10db865edc756c68f9955e92ca7b193fc6142d9ba007bb55e58eaa890d341357decede8da21c86da18033337eb43e262e79cc5378dda46212037f7a6d4bb72",
          "sha256": "7afab991cc2aeea0ad76a49cc86706b03e5e2bcafa390ac3c6d3beca55c06d71",
          "sha1": "f0051b89a897c45ee2f761e9976c78fd3de9ba98",
          "md5": "601b913f06cf1f4988f8e62af68787ad"
        }
      ]
    }
  ]
}
