{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pay_android",
    "module": "pay_android_debug",
    "version": "v1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-v1.1.2.aar",
          "url": "pay_android_debug-v1.1.2.aar",
          "size": 21112,
          "sha512": "92d1933c09fdbdca73adf9d82b20991efde3ee77592e2c47f1908efb7c07333453e2931a607f39f6b6b107b4c262015936aedadc1b3a1cfbca9959204f8d054a",
          "sha256": "3eecff2de3cba691a0aeb2fce869014a92225fea4b8c94e2dcd75f5f0d1f1c87",
          "sha1": "d823b82278cc441f6626b63b0426993c163e77e3",
          "md5": "2637af87ce4bbe025b4287d3c8fa32b1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-v1.1.2.aar",
          "url": "pay_android_debug-v1.1.2.aar",
          "size": 21112,
          "sha512": "92d1933c09fdbdca73adf9d82b20991efde3ee77592e2c47f1908efb7c07333453e2931a607f39f6b6b107b4c262015936aedadc1b3a1cfbca9959204f8d054a",
          "sha256": "3eecff2de3cba691a0aeb2fce869014a92225fea4b8c94e2dcd75f5f0d1f1c87",
          "sha1": "d823b82278cc441f6626b63b0426993c163e77e3",
          "md5": "2637af87ce4bbe025b4287d3c8fa32b1"
        }
      ]
    }
  ]
}
