{
  "formatVersion": "1.1",
  "component": {
    "group": "net.touchcapture.qr.flutterqr",
    "module": "qr_code_scanner_debug",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_debug-2.4.0.aar",
          "url": "qr_code_scanner_debug-2.4.0.aar",
          "size": 37433,
          "sha512": "5e3eb2e001f7866bf9134f9793798cfd9d16dc67a047dbe865cc5f7f6ad52e17387fe850057ca7d02b5636d544707918a16edc301e07d22feee270139ed15988",
          "sha256": "eb6383bcab51a3a4da18e82322b3d7bc8cf4724898ebe96bfbda75e4c49c02a6",
          "sha1": "41a5800a39240e30aa1304cbc61abc296e31fe9d",
          "md5": "8781bf1afffd13a36c35530133103781"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_debug-2.4.0.aar",
          "url": "qr_code_scanner_debug-2.4.0.aar",
          "size": 37433,
          "sha512": "5e3eb2e001f7866bf9134f9793798cfd9d16dc67a047dbe865cc5f7f6ad52e17387fe850057ca7d02b5636d544707918a16edc301e07d22feee270139ed15988",
          "sha256": "eb6383bcab51a3a4da18e82322b3d7bc8cf4724898ebe96bfbda75e4c49c02a6",
          "sha1": "41a5800a39240e30aa1304cbc61abc296e31fe9d",
          "md5": "8781bf1afffd13a36c35530133103781"
        }
      ]
    }
  ]
}
