{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flutternetwork.wifi.wifi_scan",
    "module": "wifi_scan_debug",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_debug-2.0.0.aar",
          "url": "wifi_scan_debug-2.0.0.aar",
          "size": 20343,
          "sha512": "f5f671f92680e1d70208dc797141ef4e8d96304ed8aa29883ee49b6c5cab5163abf1b35ca670f373bea0f01529c01060105b6f97dacb8cd9bb0a386113aaaf45",
          "sha256": "50c92f25579aff07da2ab14950497aafe4db10d3add2d0f259f68ee2094ff412",
          "sha1": "254f966e5f1dd6fe7cf5d0ab5d96c6ae68ecf5a5",
          "md5": "9eb342f720e8d081703509dac2c86364"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_debug-2.0.0.aar",
          "url": "wifi_scan_debug-2.0.0.aar",
          "size": 20343,
          "sha512": "f5f671f92680e1d70208dc797141ef4e8d96304ed8aa29883ee49b6c5cab5163abf1b35ca670f373bea0f01529c01060105b6f97dacb8cd9bb0a386113aaaf45",
          "sha256": "50c92f25579aff07da2ab14950497aafe4db10d3add2d0f259f68ee2094ff412",
          "sha1": "254f966e5f1dd6fe7cf5d0ab5d96c6ae68ecf5a5",
          "md5": "9eb342f720e8d081703509dac2c86364"
        }
      ]
    }
  ]
}
