{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_profile",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-v1.0.0.aar",
          "url": "connectivity_plus_profile-v1.0.0.aar",
          "size": 9034,
          "sha512": "105b5ddcdc867a11a1a92271980b8c6c52f3b4c5f358fd621b747993befd3fd85825eb363ecce4772c1276c1f4c71c25bdc01cd0d2a16a0bd6644432c3f6cb12",
          "sha256": "94c66ad8b5d6cc9ac870c2f2f0b6ca78b4dd93826eeaa9949f863ee9e5a0a9f2",
          "sha1": "52d19a9b6a4c12f9ce91121a1b87f171c9b6b6f7",
          "md5": "dc58e2d9dedffb3789dc680538f2326e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-v1.0.0.aar",
          "url": "connectivity_plus_profile-v1.0.0.aar",
          "size": 9034,
          "sha512": "105b5ddcdc867a11a1a92271980b8c6c52f3b4c5f358fd621b747993befd3fd85825eb363ecce4772c1276c1f4c71c25bdc01cd0d2a16a0bd6644432c3f6cb12",
          "sha256": "94c66ad8b5d6cc9ac870c2f2f0b6ca78b4dd93826eeaa9949f863ee9e5a0a9f2",
          "sha1": "52d19a9b6a4c12f9ce91121a1b87f171c9b6b6f7",
          "md5": "dc58e2d9dedffb3789dc680538f2326e"
        }
      ]
    }
  ]
}
