{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_release",
    "version": "v1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v1.1.1.aar",
          "url": "flutter_release-v1.1.1.aar",
          "size": 35163933,
          "sha512": "b6f0a4a19f3ec999500165a88dac8819daa952757698a1ba4a3da7d9d1797ad9ed76f61033296ef3f3ed0633134fee8ff8b608e69311d0fa26ac6b0b8ccc6974",
          "sha256": "16f85932bd275dd3430d8a2ed0a82e219fa0011a2c260f51877bb2c3bcfb7d4f",
          "sha1": "971a7d99854b8fd5af0f5b0416acd65817c2e8c3",
          "md5": "f6d0d64f4827aca2d74f1b226d962941"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v1.1.1.aar",
          "url": "flutter_release-v1.1.1.aar",
          "size": 35163933,
          "sha512": "b6f0a4a19f3ec999500165a88dac8819daa952757698a1ba4a3da7d9d1797ad9ed76f61033296ef3f3ed0633134fee8ff8b608e69311d0fa26ac6b0b8ccc6974",
          "sha256": "16f85932bd275dd3430d8a2ed0a82e219fa0011a2c260f51877bb2c3bcfb7d4f",
          "sha1": "971a7d99854b8fd5af0f5b0416acd65817c2e8c3",
          "md5": "f6d0d64f4827aca2d74f1b226d962941"
        }
      ]
    }
  ]
}
