{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_release",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-2.2.3.aar",
          "url": "flutter_release-2.2.3.aar",
          "size": 35923436,
          "sha512": "5d7f24074401b889c3eea9744f79480a753559a18e4dc9db432cd420c95d84ffc70d51b7c2297c911fa8268f779a3299dc92f69510a5db6b1f3fcc86ccf759e2",
          "sha256": "0527027afb401b0e49da944fbadf0069f477c251ebc681565525a32c21ef62ca",
          "sha1": "72737d88c1b3faea74729f16d5fe4e209075ccb7",
          "md5": "5f04fe17be4c4e63a3f5f84e7b354dfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-2.2.3.aar",
          "url": "flutter_release-2.2.3.aar",
          "size": 35923436,
          "sha512": "5d7f24074401b889c3eea9744f79480a753559a18e4dc9db432cd420c95d84ffc70d51b7c2297c911fa8268f779a3299dc92f69510a5db6b1f3fcc86ccf759e2",
          "sha256": "0527027afb401b0e49da944fbadf0069f477c251ebc681565525a32c21ef62ca",
          "sha1": "72737d88c1b3faea74729f16d5fe4e209075ccb7",
          "md5": "5f04fe17be4c4e63a3f5f84e7b354dfa"
        }
      ]
    }
  ]
}
