{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni_flutter",
    "module": "jni_flutter_profile",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "jni_flutter_profile-2.2.0.aar",
          "url": "jni_flutter_profile-2.2.0.aar",
          "size": 2506,
          "sha512": "18974504cba098101810bde2b3e70198c4d8db98f1341ebe015d161d94e805c310a585e2af7656263a835d50f5b744976ab520055e2c935ff2f78746e039139b",
          "sha256": "669865732504f8020b5d00988e04772ca4bf11bd64967cf519e1719281244d97",
          "sha1": "1b71c98ac949320b6631cd8c213ee1fe029a10c3",
          "md5": "83a38cfe33ccea1668b8f7b16264d75f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_profile",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "jni_flutter_profile-2.2.0.aar",
          "url": "jni_flutter_profile-2.2.0.aar",
          "size": 2506,
          "sha512": "18974504cba098101810bde2b3e70198c4d8db98f1341ebe015d161d94e805c310a585e2af7656263a835d50f5b744976ab520055e2c935ff2f78746e039139b",
          "sha256": "669865732504f8020b5d00988e04772ca4bf11bd64967cf519e1719281244d97",
          "sha1": "1b71c98ac949320b6631cd8c213ee1fe029a10c3",
          "md5": "83a38cfe33ccea1668b8f7b16264d75f"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_flutter_profile-2.2.0-sources.jar",
          "url": "jni_flutter_profile-2.2.0-sources.jar",
          "size": 1655,
          "sha512": "7a07c72930ea5c442e303f2c17de9b67451b778a59b70d46cadbbfba1a48ec54c6064ed8a8771f3ebac9b4be5a1b590cb73c91f5950db32157c4fbee15a9df72",
          "sha256": "85b049ada44240ce31ffe69985466e9c9fd424e24a293e396576b61f5fefe1b0",
          "sha1": "e3f68df4cf7ea0164890430e8e8a91074584481f",
          "md5": "6ea4b0d8e6f41190c6261b40de37e7b4"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_flutter_profile-2.2.0-javadoc.jar",
          "url": "jni_flutter_profile-2.2.0-javadoc.jar",
          "size": 264622,
          "sha512": "5bb65f681b2f578eb67321754ec81960a9b74a7d346e4c6c27c7223a05207244e01660388362823589f17b6f83d9ecc6c90a826e80538da55f75ba60803065d8",
          "sha256": "9a4084878bac14c2e77f38c72bdb5b6460b8d873adb30d752b2c48280800e2cb",
          "sha1": "46b84dfae3e38e151d23b43d268f3ab237727285",
          "md5": "9990e6dfa3bfc49387ee69dcec3eb145"
        }
      ]
    }
  ]
}
