{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_profile",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-2.2.3.aar",
          "url": "sqflite_profile-2.2.3.aar",
          "size": 45180,
          "sha512": "94ccde75e75bbce121e2d123c77713d92d37afa7783fb18d6d8a6afa922894ce53273ec57e64fc7369358a59bad92f92c93ac8e610402a55b67e304c86a7ff36",
          "sha256": "868f04e8831d023ce7537d0e258fbf2a7c32dc28008ee0f62ec1b47486acf522",
          "sha1": "15667eaee24196031df29a4625a2b23cd986755b",
          "md5": "674a27f0c20103c4f6d1954d7c2e4384"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-2.2.3.aar",
          "url": "sqflite_profile-2.2.3.aar",
          "size": 45180,
          "sha512": "94ccde75e75bbce121e2d123c77713d92d37afa7783fb18d6d8a6afa922894ce53273ec57e64fc7369358a59bad92f92c93ac8e610402a55b67e304c86a7ff36",
          "sha256": "868f04e8831d023ce7537d0e258fbf2a7c32dc28008ee0f62ec1b47486acf522",
          "sha1": "15667eaee24196031df29a4625a2b23cd986755b",
          "md5": "674a27f0c20103c4f6d1954d7c2e4384"
        }
      ]
    }
  ]
}
