{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_debug",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.fingerprintjs.flutter.fpjs_pro.fpjs_pro_plugin",
          "module": "fpjs_pro_plugin_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-2.0.0.aar",
          "url": "flutter_debug-2.0.0.aar",
          "size": 47245218,
          "sha512": "752eda921b620b2622bc89edc99abdde30dcf826148c9fe541a5555687f377cc31dcf519fe8738e303f435b43d1e1a5e661f77218324347ef66ecce2baa582f3",
          "sha256": "84e4c956386a4f11082a8e03027832452bad2ae1314002b86f3744e9e62c97e4",
          "sha1": "c7511f3ec0d63b551cb90b32aa4f02d66e643d09",
          "md5": "729d45d4e282620cdeba2f31d451ff22"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.fingerprintjs.flutter.fpjs_pro.fpjs_pro_plugin",
          "module": "fpjs_pro_plugin_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-2.0.0.aar",
          "url": "flutter_debug-2.0.0.aar",
          "size": 47245218,
          "sha512": "752eda921b620b2622bc89edc99abdde30dcf826148c9fe541a5555687f377cc31dcf519fe8738e303f435b43d1e1a5e661f77218324347ef66ecce2baa582f3",
          "sha256": "84e4c956386a4f11082a8e03027832452bad2ae1314002b86f3744e9e62c97e4",
          "sha1": "c7511f3ec0d63b551cb90b32aa4f02d66e643d09",
          "md5": "729d45d4e282620cdeba2f31d451ff22"
        }
      ]
    }
  ]
}
