{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-2.2.0rc1.aar",
          "url": "webview_flutter_android_debug-2.2.0rc1.aar",
          "size": 281713,
          "sha512": "3a5beb0ccc3b2b7454842fcaa744ff0b732de2ecbbddc5b0fccaee9af92c8a5cc4e719eb87c713a79a89525a44760c63c9bbbf1afdad8a5ce6c8ac71865ac6ce",
          "sha256": "66b8130e34b738ed6099bc2b5e795eae1e7fb192495d247b42ad15f16cb02a18",
          "sha1": "2ed4a8844ff506cae0782f612bdf5fa5743c88b9",
          "md5": "cbb2fe5f81689d55a821173a02994b3e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-2.2.0rc1.aar",
          "url": "webview_flutter_android_debug-2.2.0rc1.aar",
          "size": 281713,
          "sha512": "3a5beb0ccc3b2b7454842fcaa744ff0b732de2ecbbddc5b0fccaee9af92c8a5cc4e719eb87c713a79a89525a44760c63c9bbbf1afdad8a5ce6c8ac71865ac6ce",
          "sha256": "66b8130e34b738ed6099bc2b5e795eae1e7fb192495d247b42ad15f16cb02a18",
          "sha1": "2ed4a8844ff506cae0782f612bdf5fa5743c88b9",
          "md5": "cbb2fe5f81689d55a821173a02994b3e"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_debug-2.2.0rc1-sources.jar",
          "url": "webview_flutter_android_debug-2.2.0rc1-sources.jar",
          "size": 61672,
          "sha512": "986c5aa1d166cef12d3d4eaaf652636388c1b06d993169f83810790eb66bc579833fb64df4b88335176df2341bfdfdf6dbce69fb41e9da565c9ee067c5085918",
          "sha256": "3a0ce9de3c1fe73164306fa437316145e9eb13ee478c7d2171ce7051750abf53",
          "sha1": "a0ad416109d6d45590d981ecf289e204bd033295",
          "md5": "526a7c1af86e378623197367f4cfbcb9"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_debug-2.2.0rc1-javadoc.jar",
          "url": "webview_flutter_android_debug-2.2.0rc1-javadoc.jar",
          "size": 751948,
          "sha512": "4b0e1ffef57a52d0e899d97c11022732e00ab06682f5dc35f17f92768886cafcb6413eb7436d6c64dbb95074999b351ecfa11349a37b5033970db44c49ed818e",
          "sha256": "b171062caa6d239c3ab8cd44fbe4344de9438d89336a2661ac1f404e293e38d2",
          "sha1": "a8512bef789abc717969cf2a1ad6d23bcbe9a0e2",
          "md5": "6033d12ad5f8de577b10e7c99b268522"
        }
      ]
    }
  ]
}
