{
  "formatVersion": "1.1",
  "component": {
    "group": "com.empactit.empactit_wifi",
    "module": "empactit_wifi_release",
    "version": "v1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-v1.1.1.aar",
          "url": "empactit_wifi_release-v1.1.1.aar",
          "size": 5769,
          "sha512": "8bbfc1c1f42051da709fc4fd2afb13315b188cc4f46b2ee135e53cf9fca50237856827734c5e334240fdfdcb79a854b2240228da7df74b750167bc2cad289956",
          "sha256": "adee31b183203d5dd570d3b00534dbe4c40a01ffdfa3e092898d23fd1f5f8dda",
          "sha1": "979927f6d35c6c45c13718e9335d94e81a834959",
          "md5": "c39a10b6b65c7be3de51e081559b55cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-v1.1.1.aar",
          "url": "empactit_wifi_release-v1.1.1.aar",
          "size": 5769,
          "sha512": "8bbfc1c1f42051da709fc4fd2afb13315b188cc4f46b2ee135e53cf9fca50237856827734c5e334240fdfdcb79a854b2240228da7df74b750167bc2cad289956",
          "sha256": "adee31b183203d5dd570d3b00534dbe4c40a01ffdfa3e092898d23fd1f5f8dda",
          "sha1": "979927f6d35c6c45c13718e9335d94e81a834959",
          "md5": "c39a10b6b65c7be3de51e081559b55cf"
        }
      ]
    }
  ]
}
