{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-2.2.3.aar",
          "url": "url_launcher_android_debug-2.2.3.aar",
          "size": 22459,
          "sha512": "3641405d668f78980b260bae958e526686a26a751b73cf3780d5dcb1f3d3fbb55fca66a9f21f0713984b30d1b5bf2549c1d6d62f99f5d808331046d3268d654f",
          "sha256": "f93360502bd86f5bde38ce1f56577a4abe23fa5fb98e8438ec47fa16c474876f",
          "sha1": "d8985fe83bbb25c78d17a741bf5adc657338f7ff",
          "md5": "ce29e935e3b1e72aa17dc587427d5a2f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-2.2.3.aar",
          "url": "url_launcher_android_debug-2.2.3.aar",
          "size": 22459,
          "sha512": "3641405d668f78980b260bae958e526686a26a751b73cf3780d5dcb1f3d3fbb55fca66a9f21f0713984b30d1b5bf2549c1d6d62f99f5d808331046d3268d654f",
          "sha256": "f93360502bd86f5bde38ce1f56577a4abe23fa5fb98e8438ec47fa16c474876f",
          "sha1": "d8985fe83bbb25c78d17a741bf5adc657338f7ff",
          "md5": "ce29e935e3b1e72aa17dc587427d5a2f"
        }
      ]
    }
  ]
}
