{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "2.0.0rc3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-2.0.0rc3.aar",
          "url": "webview_flutter_android_release-2.0.0rc3.aar",
          "size": 107071,
          "sha512": "578b36b5b686cfb002dd714c6c21df0ac32741396bd31ee098ee1b2afa5479d75b97943ea978cb53be09f596ccbee2ac6167d129b359c34637a365aeae2f4934",
          "sha256": "4c133acb5a8636d6dcff6b8601316155c23a33d1f5dab2cf1c15c9ba21c18e06",
          "sha1": "b0430bfaf86066ca996b0ad2cd9bcfa869e7a02d",
          "md5": "43f9ce555e8393d79c9dd7210ddbff94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-2.0.0rc3.aar",
          "url": "webview_flutter_android_release-2.0.0rc3.aar",
          "size": 107071,
          "sha512": "578b36b5b686cfb002dd714c6c21df0ac32741396bd31ee098ee1b2afa5479d75b97943ea978cb53be09f596ccbee2ac6167d129b359c34637a365aeae2f4934",
          "sha256": "4c133acb5a8636d6dcff6b8601316155c23a33d1f5dab2cf1c15c9ba21c18e06",
          "sha1": "b0430bfaf86066ca996b0ad2cd9bcfa869e7a02d",
          "md5": "43f9ce555e8393d79c9dd7210ddbff94"
        }
      ]
    }
  ]
}
