{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-2.1.0.aar",
          "size": 4762,
          "sha512": "a61844d4ca3a9ae9e4bbd9ce2e9fb3d3b10e3b35eab1a6d4695a8484c6bafec8aede17c68113e8639678ec1aea2e282538d4285aeb5be4c39d8eed2012150cad",
          "sha256": "50664a0d818c057d31dbb2b091ec45d937a27372d226a26bf5fe86dd1c85340f",
          "sha1": "09bf823c1d81cfe5f29df7a5bc89b10ced1c449c",
          "md5": "6e77f2b5d7c8466345de282a0cce09e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-2.1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-2.1.0.aar",
          "size": 4762,
          "sha512": "a61844d4ca3a9ae9e4bbd9ce2e9fb3d3b10e3b35eab1a6d4695a8484c6bafec8aede17c68113e8639678ec1aea2e282538d4285aeb5be4c39d8eed2012150cad",
          "sha256": "50664a0d818c057d31dbb2b091ec45d937a27372d226a26bf5fe86dd1c85340f",
          "sha1": "09bf823c1d81cfe5f29df7a5bc89b10ced1c449c",
          "md5": "6e77f2b5d7c8466345de282a0cce09e6"
        }
      ]
    }
  ]
}
