{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_release",
    "version": "v1.1.1d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v1.1.1d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v1.1.1d.aar",
          "url": "flutter_release-v1.1.1d.aar",
          "size": 35225330,
          "sha512": "3f832d3189c0ec8e140e3a50e4dc3dbd1cd16162f6fdbc19a11966110f447edd1d5e475fd3f84ba3c8397dad1b56fbf02d8b72f2e5a957e4ae79eac1e9c51218",
          "sha256": "5093352e77cd6f47242b74b11712c770f09ddf1db2f4c0809213e95a7925d72d",
          "sha1": "b6fe85920204d36f50384a9f97890eabf53346e0",
          "md5": "ff43bb449e7c2e75c2bf21f4aef730b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "v1.1.1d"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_release",
          "version": {
            "requires": "v1.1.1d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v1.1.1d.aar",
          "url": "flutter_release-v1.1.1d.aar",
          "size": 35225330,
          "sha512": "3f832d3189c0ec8e140e3a50e4dc3dbd1cd16162f6fdbc19a11966110f447edd1d5e475fd3f84ba3c8397dad1b56fbf02d8b72f2e5a957e4ae79eac1e9c51218",
          "sha256": "5093352e77cd6f47242b74b11712c770f09ddf1db2f4c0809213e95a7925d72d",
          "sha1": "b6fe85920204d36f50384a9f97890eabf53346e0",
          "md5": "ff43bb449e7c2e75c2bf21f4aef730b2"
        }
      ]
    }
  ]
}
