{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni",
    "module": "jni_profile",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "jni_profile-2.2.0.aar",
          "url": "jni_profile-2.2.0.aar",
          "size": 109091,
          "sha512": "7e5eac99db9f2e787d46744b613d624b60d30a1a36f3e68661a98f6101df6bef0aa19c51d8532ef08bd59f263da5896511c9190ec9b6c577ca6ef1a8505ad88c",
          "sha256": "e28ff585237fe4bf13aa1dce9c1a87c9d81898d23b7844ccdae42b3719f8a522",
          "sha1": "a33b8b1c078d03ad8bfd546010dd2bf23452e38c",
          "md5": "c3824254300a527b5ba06fc4efa7c7e9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "jni_profile-2.2.0.aar",
          "url": "jni_profile-2.2.0.aar",
          "size": 109091,
          "sha512": "7e5eac99db9f2e787d46744b613d624b60d30a1a36f3e68661a98f6101df6bef0aa19c51d8532ef08bd59f263da5896511c9190ec9b6c577ca6ef1a8505ad88c",
          "sha256": "e28ff585237fe4bf13aa1dce9c1a87c9d81898d23b7844ccdae42b3719f8a522",
          "sha1": "a33b8b1c078d03ad8bfd546010dd2bf23452e38c",
          "md5": "c3824254300a527b5ba06fc4efa7c7e9"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_profile-2.2.0-sources.jar",
          "url": "jni_profile-2.2.0-sources.jar",
          "size": 5459,
          "sha512": "61c8d0b11708383673e2d967abe5948df4f9f1c20f77852bfc8e4da61a83bb5c2e7561a02692dc183a64b4f842555d66ebd142d02b6295313fcda91f9e8e0c15",
          "sha256": "0762cdfe1e25701b53f0e55fde69135e74f25328f4b1c60e4778701833bfab6e",
          "sha1": "09a60f323f1b590e7921cd33327514fe4d916cb1",
          "md5": "3cf8aa129d418b4388b02cea9ff9819b"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_profile-2.2.0-javadoc.jar",
          "url": "jni_profile-2.2.0-javadoc.jar",
          "size": 283167,
          "sha512": "7a8dcf4c57ebef66a0571e985dcb50dec08b3ee32673e0628280529af980a053c486e367e2f096d56d262b8a1c19c1fa057e0ae3c1f466842826258dbe181758",
          "sha256": "466cb81679e3e5bbf68a1f230e66dd6ce3d211919fbcb368b48e655e0f3ae344",
          "sha1": "840a56d6e302dfbffe9e2eeb507dbf410ef7ecf9",
          "md5": "834053332f5ca999dcd597d7e4618a0f"
        }
      ]
    }
  ]
}
