{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-2.5.0.aar",
          "url": "url_launcher_android_release-2.5.0.aar",
          "size": 21314,
          "sha512": "f21b2359aabb5e3cfd4647989dfce08205b5e010d9c7ec9b3b85945e53b9df49c2c70931a58e8de91bb49704680907e87a1ddac7ffc04542d226072f03e1737c",
          "sha256": "3c94d14af8d3cee8c142610c57929f87edf32a8ee271a1ca2b9413da3dcf0de6",
          "sha1": "3ff4f524593273fb73af5b40fa751375af52ea76",
          "md5": "17dde0ea83e6c12f701fb3ca74c556de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-2.5.0.aar",
          "url": "url_launcher_android_release-2.5.0.aar",
          "size": 21314,
          "sha512": "f21b2359aabb5e3cfd4647989dfce08205b5e010d9c7ec9b3b85945e53b9df49c2c70931a58e8de91bb49704680907e87a1ddac7ffc04542d226072f03e1737c",
          "sha256": "3c94d14af8d3cee8c142610c57929f87edf32a8ee271a1ca2b9413da3dcf0de6",
          "sha1": "3ff4f524593273fb73af5b40fa751375af52ea76",
          "md5": "17dde0ea83e6c12f701fb3ca74c556de"
        }
      ]
    }
  ]
}
