{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_profile",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0rc1.aar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0rc1.aar",
          "size": 2528,
          "sha512": "cf1cc784716d0169096e62bd95a83d4c76baae3ff7c215dacc948445e5ad520e24da59406f25177c1505d68730ced0c93537a7404d6dc6d212c1c6fb49d409a0",
          "sha256": "1983cd47cd183a3be9a540166b49a1f82fedd2f30921ec2d2b2b3045796883a2",
          "sha1": "23cbaa6b5d30878617b127154a75fc144676f499",
          "md5": "a73bc3a2675b8ec6321c4ecc7a234815"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0rc1.aar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0rc1.aar",
          "size": 2528,
          "sha512": "cf1cc784716d0169096e62bd95a83d4c76baae3ff7c215dacc948445e5ad520e24da59406f25177c1505d68730ced0c93537a7404d6dc6d212c1c6fb49d409a0",
          "sha256": "1983cd47cd183a3be9a540166b49a1f82fedd2f30921ec2d2b2b3045796883a2",
          "sha1": "23cbaa6b5d30878617b127154a75fc144676f499",
          "md5": "a73bc3a2675b8ec6321c4ecc7a234815"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0rc1-sources.jar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0rc1-sources.jar",
          "size": 2659,
          "sha512": "d848b9ac3a80bd88694f7d35de2abc2866f65393d53caa1f49513063e17fe497a4b7e1ed09dc3736f529a166f1491dfb78c703a51f0fe0950082488869f2b352",
          "sha256": "2930f0a83f74dc7a57026b471c4443a3e5cb4f8b5f80bf45d161dd31675194c7",
          "sha1": "82b1c36d1af62197547e6c132ae64f520e3ad7a7",
          "md5": "fb7b3ee0458fe0f3ec0a8116c68f72ed"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0rc1-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0rc1-javadoc.jar",
          "size": 269839,
          "sha512": "66c6d66398b3e57c9d887c5b48666eeb7a622e662a8f869fdab9f138cd5e25853eb3a6c4675551c317d9a19824995348207cdd19532a9b4981e1e17c90aefe43",
          "sha256": "ba6acc3fd3c9cb22de266b8ab8ac5ca1fa5b5d5149790d79a32eb03b5f8e5ff1",
          "sha1": "d3156630741519896583476570894b27089b3f61",
          "md5": "6986b3b27d209233ea973c05535170ba"
        }
      ]
    }
  ]
}
