{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "v1.1.1g",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-v1.1.1g.aar",
          "url": "path_provider_android_profile-v1.1.1g.aar",
          "size": 12764,
          "sha512": "02be83147f949e57c023db7111cf9cf6ad807599f6b73dc4569a71b8477fae2b409cb5af27043ac61022cff79b221c934192d0dc418055ac3ce81598abc93254",
          "sha256": "e05edd310abb4dea2640d61becfe18999448a8bd3b3a52365a79897186c5b4a6",
          "sha1": "00654e91b81c3a2deaeec482014f370ccebfcc27",
          "md5": "9a67e8be54dfc851db44793578b60ca3"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-v1.1.1g.aar",
          "url": "path_provider_android_profile-v1.1.1g.aar",
          "size": 12764,
          "sha512": "02be83147f949e57c023db7111cf9cf6ad807599f6b73dc4569a71b8477fae2b409cb5af27043ac61022cff79b221c934192d0dc418055ac3ce81598abc93254",
          "sha256": "e05edd310abb4dea2640d61becfe18999448a8bd3b3a52365a79897186c5b4a6",
          "sha1": "00654e91b81c3a2deaeec482014f370ccebfcc27",
          "md5": "9a67e8be54dfc851db44793578b60ca3"
        }
      ]
    }
  ]
}
