{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geocoding",
    "module": "geocoding_android_debug",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "geocoding_android_debug-2.4.0.aar",
          "url": "geocoding_android_debug-2.4.0.aar",
          "size": 10852,
          "sha512": "1ac10673d3299dd810e21745c8d743d30b5f5b5f7e654e2753e8d42c389a3200ef12907edf2c1a898fda97557c9b2b0817fe6e27306e0e49324bec50f82d784d",
          "sha256": "e55ee4e6243e4b5c52d8d3bab481189c6624b433bd2c36afe3c26c618497a24a",
          "sha1": "5fb69c88a86147139d50df5b2f1e33007cff4895",
          "md5": "24020e459104cce076c194249447b2bc"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "geocoding_android_debug-2.4.0.aar",
          "url": "geocoding_android_debug-2.4.0.aar",
          "size": 10852,
          "sha512": "1ac10673d3299dd810e21745c8d743d30b5f5b5f7e654e2753e8d42c389a3200ef12907edf2c1a898fda97557c9b2b0817fe6e27306e0e49324bec50f82d784d",
          "sha256": "e55ee4e6243e4b5c52d8d3bab481189c6624b433bd2c36afe3c26c618497a24a",
          "sha1": "5fb69c88a86147139d50df5b2f1e33007cff4895",
          "md5": "24020e459104cce076c194249447b2bc"
        }
      ]
    }
  ]
}
