{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-2.1.0.aar",
          "url": "url_launcher_android_debug-2.1.0.aar",
          "size": 24493,
          "sha512": "2de1fc4f10b32b2ab3566c9766eef4669d6f43f1c67c9fea01c3d66b6b0b0cc40010d2a3e7f1b255d7675e3cbea5714d4e5da80af9351048c8d29fbde6b91798",
          "sha256": "bbb109b1e7804d83b06183014500ab5b09bae91a5b2b8a1d23b3eadd89f16ccd",
          "sha1": "20f7ad62ac2520ca199bf715da0f0a926d8646ae",
          "md5": "e5f01704994793bfd3348fdeccc5f1d7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-2.1.0.aar",
          "url": "url_launcher_android_debug-2.1.0.aar",
          "size": 24493,
          "sha512": "2de1fc4f10b32b2ab3566c9766eef4669d6f43f1c67c9fea01c3d66b6b0b0cc40010d2a3e7f1b255d7675e3cbea5714d4e5da80af9351048c8d29fbde6b91798",
          "sha256": "bbb109b1e7804d83b06183014500ab5b09bae91a5b2b8a1d23b3eadd89f16ccd",
          "sha1": "20f7ad62ac2520ca199bf715da0f0a926d8646ae",
          "md5": "e5f01704994793bfd3348fdeccc5f1d7"
        }
      ]
    }
  ]
}
