{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_debug",
    "version": "v2.0.2test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v2.0.2test.aar",
          "url": "flutter_debug-v2.0.2test.aar",
          "size": 50187842,
          "sha512": "cbd20d2c706674fac43eabec9c74fd430a6743c0752bbb5564d946bc0995ea3c253fc2c857e0ed404fc66683ecbcf4953459f6f1d54e4509e46251ce0940d995",
          "sha256": "e126aac501077c97c2c4b4070bc714bc8e6c0e4f68c7c0e5e25c6e2976af2127",
          "sha1": "26488f00313bfaf4fc1414931618b0c6a4cd9221",
          "md5": "1f326c8ec4ee9225e8259074dc0becca"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v2.0.2test"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v2.0.2test.aar",
          "url": "flutter_debug-v2.0.2test.aar",
          "size": 50187842,
          "sha512": "cbd20d2c706674fac43eabec9c74fd430a6743c0752bbb5564d946bc0995ea3c253fc2c857e0ed404fc66683ecbcf4953459f6f1d54e4509e46251ce0940d995",
          "sha256": "e126aac501077c97c2c4b4070bc714bc8e6c0e4f68c7c0e5e25c6e2976af2127",
          "sha1": "26488f00313bfaf4fc1414931618b0c6a4cd9221",
          "md5": "1f326c8ec4ee9225e8259074dc0becca"
        }
      ]
    }
  ]
}
