{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_profile",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-2.1.0.aar",
          "url": "flutter_profile-2.1.0.aar",
          "size": 39977887,
          "sha512": "942a2dcdb34814c3d105e88dc7f847f543a854bcb80a0e29ffb2cb9ba2a941d22ccd4d4ab6c4f981ca5958197fc212608e71b9fb2900798ef5e4fb9f494b7088",
          "sha256": "d2615f0e8dd304ef5b5f2650c62aa338c6a066b7a9a7a41952b80e441b656162",
          "sha1": "eb5556308ac09f1664085936e93927565903e3fe",
          "md5": "1e14de131485dc8e105b4aa983a84603"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-2.1.0.aar",
          "url": "flutter_profile-2.1.0.aar",
          "size": 39977887,
          "sha512": "942a2dcdb34814c3d105e88dc7f847f543a854bcb80a0e29ffb2cb9ba2a941d22ccd4d4ab6c4f981ca5958197fc212608e71b9fb2900798ef5e4fb9f494b7088",
          "sha256": "d2615f0e8dd304ef5b5f2650c62aa338c6a066b7a9a7a41952b80e441b656162",
          "sha1": "eb5556308ac09f1664085936e93927565903e3fe",
          "md5": "1e14de131485dc8e105b4aa983a84603"
        }
      ]
    }
  ]
}
