{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pay_android",
    "module": "pay_android_debug",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-2.2.0rc1.aar",
          "url": "pay_android_debug-2.2.0rc1.aar",
          "size": 23639,
          "sha512": "3ef8c337c32cb05924d77255f9b0bb4948ae762f53e6028f73cce508c576c0ea168d4175cbf10313526e9910f645cc71819f58eb5d7d5a04588b2437c1181d06",
          "sha256": "347e1e877f02d8371c84acc9a17d0dd50c89d0a84e30fe7d7cfe03e6ab11b676",
          "sha1": "68fbed2317c113f2747f1525d4713dc8cf6be3a0",
          "md5": "36cd5466d4c21749d77b22bb2f7a64a1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-2.2.0rc1.aar",
          "url": "pay_android_debug-2.2.0rc1.aar",
          "size": 23639,
          "sha512": "3ef8c337c32cb05924d77255f9b0bb4948ae762f53e6028f73cce508c576c0ea168d4175cbf10313526e9910f645cc71819f58eb5d7d5a04588b2437c1181d06",
          "sha256": "347e1e877f02d8371c84acc9a17d0dd50c89d0a84e30fe7d7cfe03e6ab11b676",
          "sha1": "68fbed2317c113f2747f1525d4713dc8cf6be3a0",
          "md5": "36cd5466d4c21749d77b22bb2f7a64a1"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_debug-2.2.0rc1-sources.jar",
          "url": "pay_android_debug-2.2.0rc1-sources.jar",
          "size": 10545,
          "sha512": "9d221a27d20dfec7d3231a4e60e1a52ddaeb2da9a17857ceeefcea17a688d17fb7da85acf447bf7316e68ab5b78242fd42de5a63a56e62fca6a1f57c9742a212",
          "sha256": "a44f1227c059eb244c6dd77dadc853258f99a65a992761c3ec7ab714a42e09db",
          "sha1": "46924b9a413b27324d4be1c478d959a7a3f15490",
          "md5": "079d17719b0832269738a4ae2ab18108"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_debug-2.2.0rc1-javadoc.jar",
          "url": "pay_android_debug-2.2.0rc1-javadoc.jar",
          "size": 307787,
          "sha512": "c29ee17995fb42c4471679b9aeaa5984e9d100b4a3a7eea151b97a7646fe01e75a19c912c114fe8c62ec7a0211aa3ba7730e6f61640c9a33fe7229b731afac41",
          "sha256": "736d289c7128bdccddf94b7d9f8a5894f2e51c95232e99781b149376502cade5",
          "sha1": "9dc14adb70ac39d88836632b9db6e3a64058e4cf",
          "md5": "9214d7aba1731ba3fd7a8210f7f20c10"
        }
      ]
    }
  ]
}
