{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-2.2.0rc1.aar",
          "url": "device_info_plus_release-2.2.0rc1.aar",
          "size": 7509,
          "sha512": "86efe4df2cec64aca60407587347e60eb63fefe455b4b9c5b31bd5aef5ad2ba52b067af768ee55e8b36435a534914600659a0d5cba4d24483aa200ad5851cf0d",
          "sha256": "bd2439fe1219c866f69a1e18f4dd47f29be21273d2e6f93908ba8e2126fd3f48",
          "sha1": "eea02f4ec29ad7cc7da076184c02bb5db2d0011d",
          "md5": "36828ad5031818eff3848c0b3ddb24c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-2.2.0rc1.aar",
          "url": "device_info_plus_release-2.2.0rc1.aar",
          "size": 7509,
          "sha512": "86efe4df2cec64aca60407587347e60eb63fefe455b4b9c5b31bd5aef5ad2ba52b067af768ee55e8b36435a534914600659a0d5cba4d24483aa200ad5851cf0d",
          "sha256": "bd2439fe1219c866f69a1e18f4dd47f29be21273d2e6f93908ba8e2126fd3f48",
          "sha1": "eea02f4ec29ad7cc7da076184c02bb5db2d0011d",
          "md5": "36828ad5031818eff3848c0b3ddb24c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-2.2.0rc1-sources.jar",
          "url": "device_info_plus_release-2.2.0rc1-sources.jar",
          "size": 3125,
          "sha512": "b9cb00c45bc93bb579209e570cc6bccd93db4bc096aa171224af075e8692c8781fa658075ca0fac74487a49fa688512631128c1179a925ebcfc7e0df2ac1c49f",
          "sha256": "881c3ff7cebe7fa7dcbc12c9cd124932bc1986640af6e78c69608b8c0a68b939",
          "sha1": "baedb19f71c1d446920d5e7702e29ce5e368c7d4",
          "md5": "cd8cd56bd2b0956e8e0eb8238a55e8dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-2.2.0rc1-javadoc.jar",
          "url": "device_info_plus_release-2.2.0rc1-javadoc.jar",
          "size": 260831,
          "sha512": "0bec0cbb889306edd8b92f2141dd41c0b953a7526cfb56b3a518dd21c11552ac607ee732196e9781e6e6a7dbd4677c1e5a4a3fb52f85bf850bf918b5d4579bd6",
          "sha256": "9393836861160e7a072b789f9d50c045f3f6c2b89cd92942f9748f165624417c",
          "sha1": "652bf75b453cfc4ae97e2538a43fd999cb8ec7b9",
          "md5": "a4739b3702bdece7ed4f726358befb40"
        }
      ]
    }
  ]
}
