{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pay_android",
    "module": "pay_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-1.0.aar",
          "url": "pay_android_debug-1.0.aar",
          "size": 21117,
          "sha512": "471b7e62020192245a0e419d7ac929bb14fbe3dd8c04d6e9610c8a22398467d9c9a6886d7f2f55d6d3518bad3d5ce4dfebab7d8cda38402a04b072f6ea2e37be",
          "sha256": "39c2a050ddde22e6ace820feab7bab772417f2e9fd50a0b877e80462ba15b302",
          "sha1": "d899efcaf321524ca779a5f7c83e4f2c8008b675",
          "md5": "d31c9d0ad21a7ccf167ebd7644f3532f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-1.0.aar",
          "url": "pay_android_debug-1.0.aar",
          "size": 21117,
          "sha512": "471b7e62020192245a0e419d7ac929bb14fbe3dd8c04d6e9610c8a22398467d9c9a6886d7f2f55d6d3518bad3d5ce4dfebab7d8cda38402a04b072f6ea2e37be",
          "sha256": "39c2a050ddde22e6ace820feab7bab772417f2e9fd50a0b877e80462ba15b302",
          "sha1": "d899efcaf321524ca779a5f7c83e4f2c8008b675",
          "md5": "d31c9d0ad21a7ccf167ebd7644f3532f"
        }
      ]
    }
  ]
}
