{
  "formatVersion": "1.1",
  "component": {
    "group": "com.danieldallos.storeredirect",
    "module": "store_redirect_release",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_release-2.1.4.aar",
          "url": "store_redirect_release-2.1.4.aar",
          "size": 4842,
          "sha512": "3c4dfa04bbd5166ee20c777051e8646fd180e33bd61d242aaf3e3e46af1fdb44f64ed63ed53afd1d744c577539af539812fababe5157a58387ce785b2fa8df11",
          "sha256": "e906923f247017e7169cbae197d3ac66e655d612dcbddbfd14912b1581db5f80",
          "sha1": "2f35181f8fa5bc6675c5b734ca0c43670f821ffb",
          "md5": "5c33bc2dfba5c63874a732b947633227"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_release-2.1.4.aar",
          "url": "store_redirect_release-2.1.4.aar",
          "size": 4842,
          "sha512": "3c4dfa04bbd5166ee20c777051e8646fd180e33bd61d242aaf3e3e46af1fdb44f64ed63ed53afd1d744c577539af539812fababe5157a58387ce785b2fa8df11",
          "sha256": "e906923f247017e7169cbae197d3ac66e655d612dcbddbfd14912b1581db5f80",
          "sha1": "2f35181f8fa5bc6675c5b734ca0c43670f821ffb",
          "md5": "5c33bc2dfba5c63874a732b947633227"
        }
      ]
    }
  ]
}
