{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_debug",
    "version": "v1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-v1.1.0.aar",
          "url": "connectivity_plus_debug-v1.1.0.aar",
          "size": 9399,
          "sha512": "cbb7fe2fa24e860e806f2242f89fa8290ea55a735f0551b539b7c951342ca9087721d3316d39eb1c9bc844aa4dc489dfc4ad7a6184981348832895b70f3214b9",
          "sha256": "e00e8423287a95755e906607dbb8e258f9a15b901b52b721f25c037466435ef0",
          "sha1": "87eb6535420b28fb31425c9bbeddb05640e305e3",
          "md5": "4beba45e5b26e1edc9cd6ce0208e06ac"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-v1.1.0.aar",
          "url": "connectivity_plus_debug-v1.1.0.aar",
          "size": 9399,
          "sha512": "cbb7fe2fa24e860e806f2242f89fa8290ea55a735f0551b539b7c951342ca9087721d3316d39eb1c9bc844aa4dc489dfc4ad7a6184981348832895b70f3214b9",
          "sha256": "e00e8423287a95755e906607dbb8e258f9a15b901b52b721f25c037466435ef0",
          "sha1": "87eb6535420b28fb31425c9bbeddb05640e305e3",
          "md5": "4beba45e5b26e1edc9cd6ce0208e06ac"
        }
      ]
    }
  ]
}
