{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_debug",
    "version": "v2.0.1rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v2.0.1rc1.aar",
          "url": "flutter_debug-v2.0.1rc1.aar",
          "size": 50187844,
          "sha512": "e4733fcc26f50c64c12bb88f6a9379326c73c98bcb144789aa8f3269521c4812234f6e9aba27bb6f41ed37b5ad9569f4bbf5629f14211a5e2fe8b5a7f4b8e5ea",
          "sha256": "6a9f288282fa2e2e2fdc64e9e177e707e74d9dcddbba7a616f64465bd0e79aaa",
          "sha1": "b94997b4f624363fa3257bed6793436311e45f70",
          "md5": "fbae4beb9f93d9ef5f912a763f493cca"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_debug",
          "version": {
            "requires": "v2.0.1rc1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v2.0.1rc1.aar",
          "url": "flutter_debug-v2.0.1rc1.aar",
          "size": 50187844,
          "sha512": "e4733fcc26f50c64c12bb88f6a9379326c73c98bcb144789aa8f3269521c4812234f6e9aba27bb6f41ed37b5ad9569f4bbf5629f14211a5e2fe8b5a7f4b8e5ea",
          "sha256": "6a9f288282fa2e2e2fdc64e9e177e707e74d9dcddbba7a616f64465bd0e79aaa",
          "sha1": "b94997b4f624363fa3257bed6793436311e45f70",
          "md5": "fbae4beb9f93d9ef5f912a763f493cca"
        }
      ]
    }
  ]
}
