{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "v1.1.1h",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-v1.1.1h.aar",
          "url": "shared_preferences_android_debug-v1.1.1h.aar",
          "size": 13522,
          "sha512": "8dc94089ff71b96b172dc796f74710392c28e83bfc2a36308946421eeb5c19fa61105f01ae30e1921a53de02b998ea58acdff7520ce2a715914983f7dbb3ca2e",
          "sha256": "b8e849d868e4332dc015cd3bf566138fbf1169058f212bd7002450101b7db834",
          "sha1": "c5fad274bfbe536bad3dd52561edb982f3e76f4c",
          "md5": "5d995100ac41f43520984c84ae293f5f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-v1.1.1h.aar",
          "url": "shared_preferences_android_debug-v1.1.1h.aar",
          "size": 13522,
          "sha512": "8dc94089ff71b96b172dc796f74710392c28e83bfc2a36308946421eeb5c19fa61105f01ae30e1921a53de02b998ea58acdff7520ce2a715914983f7dbb3ca2e",
          "sha256": "b8e849d868e4332dc015cd3bf566138fbf1169058f212bd7002450101b7db834",
          "sha1": "c5fad274bfbe536bad3dd52561edb982f3e76f4c",
          "md5": "5d995100ac41f43520984c84ae293f5f"
        }
      ]
    }
  ]
}
