{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_profile",
    "version": "2.0.0rc3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-2.0.0rc3.aar",
          "url": "flutter_profile-2.0.0rc3.aar",
          "size": 39739255,
          "sha512": "41c51a7ca7cc3427fecd87135c46c8736ebe4975e0b88e93a185349eed5ddd02803e7c1d80047c2e0e810ba902658e8605dafb26c9e9df27a748100a7d2cd356",
          "sha256": "6d7d66fcd47704b40c4264387ac7b6c4f2c4b3cfbafda2630bcac4a9d5510095",
          "sha1": "295b5044f409ed93a84db33c959ed9ef4f1d50d1",
          "md5": "60220438282f9a88e287164eed1b20d4"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.baseflow.googleapiavailability",
          "module": "google_api_availability_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "2.0.0rc3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-2.0.0rc3.aar",
          "url": "flutter_profile-2.0.0rc3.aar",
          "size": 39739255,
          "sha512": "41c51a7ca7cc3427fecd87135c46c8736ebe4975e0b88e93a185349eed5ddd02803e7c1d80047c2e0e810ba902658e8605dafb26c9e9df27a748100a7d2cd356",
          "sha256": "6d7d66fcd47704b40c4264387ac7b6c4f2c4b3cfbafda2630bcac4a9d5510095",
          "sha1": "295b5044f409ed93a84db33c959ed9ef4f1d50d1",
          "md5": "60220438282f9a88e287164eed1b20d4"
        }
      ]
    }
  ]
}
