{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_profile",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0.aar",
          "size": 2528,
          "sha512": "cf1cc784716d0169096e62bd95a83d4c76baae3ff7c215dacc948445e5ad520e24da59406f25177c1505d68730ced0c93537a7404d6dc6d212c1c6fb49d409a0",
          "sha256": "1983cd47cd183a3be9a540166b49a1f82fedd2f30921ec2d2b2b3045796883a2",
          "sha1": "23cbaa6b5d30878617b127154a75fc144676f499",
          "md5": "a73bc3a2675b8ec6321c4ecc7a234815"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0.aar",
          "size": 2528,
          "sha512": "cf1cc784716d0169096e62bd95a83d4c76baae3ff7c215dacc948445e5ad520e24da59406f25177c1505d68730ced0c93537a7404d6dc6d212c1c6fb49d409a0",
          "sha256": "1983cd47cd183a3be9a540166b49a1f82fedd2f30921ec2d2b2b3045796883a2",
          "sha1": "23cbaa6b5d30878617b127154a75fc144676f499",
          "md5": "a73bc3a2675b8ec6321c4ecc7a234815"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0-sources.jar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0-sources.jar",
          "size": 2659,
          "sha512": "d848b9ac3a80bd88694f7d35de2abc2866f65393d53caa1f49513063e17fe497a4b7e1ed09dc3736f529a166f1491dfb78c703a51f0fe0950082488869f2b352",
          "sha256": "2930f0a83f74dc7a57026b471c4443a3e5cb4f8b5f80bf45d161dd31675194c7",
          "sha1": "82b1c36d1af62197547e6c132ae64f520e3ad7a7",
          "md5": "fb7b3ee0458fe0f3ec0a8116c68f72ed"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-2.2.0-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_profile-2.2.0-javadoc.jar",
          "size": 269831,
          "sha512": "6eeb099d197827dd1425e1971bdfca63cf3a2ef9e47e5b12a6251be032ea44d90cb34af438041a52e1f9262e86a804609f609ce52d638ab208a9b5378a8fe40d",
          "sha256": "591b3470485a19e5b27e7cc6c841828d019cca16ed4f65ee227657b0c9ee7584",
          "sha1": "3db8af3f4ca4ec876ca5dfe5ab5fe7ae0bef6db7",
          "md5": "4c9c649339f2cd8110945a0449fa41cb"
        }
      ]
    }
  ]
}
