{
  "formatVersion": "1.1",
  "component": {
    "group": "com.alternadom.wifiiot",
    "module": "wifi_iot_debug",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_debug-2.0.2.aar",
          "url": "wifi_iot_debug-2.0.2.aar",
          "size": 41550,
          "sha512": "c149ab9f90e556f16559e61b4a3d0964cc1503054f37f66877699dd82cefff3486fa5cfec15385d62abd56c7a78af98e931bdbbbc1e7f81697e356eb7e94a906",
          "sha256": "51d3c63d04349046c61aa709a59f98fdec58d702da5d94f99a2de1c323fca4cc",
          "sha1": "6e906e28de3243b0f3b0261108f9e2d64e1fd733",
          "md5": "814ebb5d0a354da399ea23aa19d439b2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_iot_debug-2.0.2.aar",
          "url": "wifi_iot_debug-2.0.2.aar",
          "size": 41550,
          "sha512": "c149ab9f90e556f16559e61b4a3d0964cc1503054f37f66877699dd82cefff3486fa5cfec15385d62abd56c7a78af98e931bdbbbc1e7f81697e356eb7e94a906",
          "sha256": "51d3c63d04349046c61aa709a59f98fdec58d702da5d94f99a2de1c323fca4cc",
          "sha1": "6e906e28de3243b0f3b0261108f9e2d64e1fd733",
          "md5": "814ebb5d0a354da399ea23aa19d439b2"
        }
      ]
    }
  ]
}
