{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flutternetwork.wifi.wifi_scan",
    "module": "wifi_scan_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_debug-1.0.aar",
          "url": "wifi_scan_debug-1.0.aar",
          "size": 19950,
          "sha512": "0f6f4faf7259dd501729fa7b193365c56ec02c1027c9cffa8198f2738b0efbc5a9af6db481c743b451ea9cf904cab95167167bfa1bf4896d37810f3ed4ed1dc9",
          "sha256": "fcd9d1b6b12e0fe9e22bc54b0a5f2cd4495f9d792ef258a01db70f11a704cc04",
          "sha1": "d25e8610fb7919a5c603c8e1faa3758c506d4cf6",
          "md5": "c737d3b38a541fc2c5065d3c5136a82c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_debug-1.0.aar",
          "url": "wifi_scan_debug-1.0.aar",
          "size": 19950,
          "sha512": "0f6f4faf7259dd501729fa7b193365c56ec02c1027c9cffa8198f2738b0efbc5a9af6db481c743b451ea9cf904cab95167167bfa1bf4896d37810f3ed4ed1dc9",
          "sha256": "fcd9d1b6b12e0fe9e22bc54b0a5f2cd4495f9d792ef258a01db70f11a704cc04",
          "sha1": "d25e8610fb7919a5c603c8e1faa3758c506d4cf6",
          "md5": "c737d3b38a541fc2c5065d3c5136a82c"
        }
      ]
    }
  ]
}
