{
  "formatVersion": "1.1",
  "component": {
    "group": "com.danieldallos.storeredirect",
    "module": "store_redirect_profile",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_profile-2.2.0rc1.aar",
          "url": "store_redirect_profile-2.2.0rc1.aar",
          "size": 2707,
          "sha512": "a6ddbdb671e1fa15d90fd1674e68b8cd06efe758db87bb9cda87050cb47bc7bdb3d6f1104ab518650419f8571f0d2344f5e6bd8923956e6221b6784f4eeb9e79",
          "sha256": "640fa46969e4c492842d54d26aa4abf8bc30351628d7c96b64f66d9901080dc1",
          "sha1": "7e43fa4226dc5447884ab88833f6b8b73ab0ee64",
          "md5": "666a651886a25a05dda31d395c11e202"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "store_redirect_profile-2.2.0rc1.aar",
          "url": "store_redirect_profile-2.2.0rc1.aar",
          "size": 2707,
          "sha512": "a6ddbdb671e1fa15d90fd1674e68b8cd06efe758db87bb9cda87050cb47bc7bdb3d6f1104ab518650419f8571f0d2344f5e6bd8923956e6221b6784f4eeb9e79",
          "sha256": "640fa46969e4c492842d54d26aa4abf8bc30351628d7c96b64f66d9901080dc1",
          "sha1": "7e43fa4226dc5447884ab88833f6b8b73ab0ee64",
          "md5": "666a651886a25a05dda31d395c11e202"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "store_redirect_profile-2.2.0rc1-sources.jar",
          "url": "store_redirect_profile-2.2.0rc1-sources.jar",
          "size": 1534,
          "sha512": "472be5e971a78ba72f9d896169f9f716bfe6036063785d32f623bf6028767d3e46d2b4c90f660cd70c8292017c7f77d1077f7d5644b24ab8a888df57a63bf04f",
          "sha256": "da42ed85e4160ae713a439a854534f4d5c7e527e08912de1c051f741d96fc11c",
          "sha1": "a63c47d8f23f1601e036680b6c016e2fc32752da",
          "md5": "3bd166fe51705a742b86ea3d051a4305"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "store_redirect_profile-2.2.0rc1-javadoc.jar",
          "url": "store_redirect_profile-2.2.0rc1-javadoc.jar",
          "size": 262598,
          "sha512": "acc9af712ec24027c8843532c2268f1bc53e6a880d5496cf4bcd6f31061798a8e374fa4d6b1a60f4920f086e79811b1fa4b95f8bfe00ba2f35f56cbacc277f83",
          "sha256": "da36f0c2e3e26145f4832c326a9e27061a6a4e33d5eda4ac9be84fa97632fb6f",
          "sha1": "d4155bf0b18e0d00cffa131ba21fe75b6548f5ee",
          "md5": "262ad6d15d98f757cc07d452f7f90d65"
        }
      ]
    }
  ]
}
