{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-2.2.0rc1.aar",
          "url": "permission_handler_android_profile-2.2.0rc1.aar",
          "size": 27817,
          "sha512": "cba231eec3a642bd6ba484d6e7a0b17fccc6662e3efd8ff46fd4eef1a68bfb81397985a01e706cf045e7e77f2b4c25ebe881ba41db65091bce1f1954915dd22e",
          "sha256": "ee148a4028ba158e73bd722cda9bed0645264e93ad749c921ef8627961f87f31",
          "sha1": "c1bbad971f1feb8af896c75738afda75bb0f0224",
          "md5": "fda13be3e12dd24d3ca5fa6df3c2d554"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-2.2.0rc1.aar",
          "url": "permission_handler_android_profile-2.2.0rc1.aar",
          "size": 27817,
          "sha512": "cba231eec3a642bd6ba484d6e7a0b17fccc6662e3efd8ff46fd4eef1a68bfb81397985a01e706cf045e7e77f2b4c25ebe881ba41db65091bce1f1954915dd22e",
          "sha256": "ee148a4028ba158e73bd722cda9bed0645264e93ad749c921ef8627961f87f31",
          "sha1": "c1bbad971f1feb8af896c75738afda75bb0f0224",
          "md5": "fda13be3e12dd24d3ca5fa6df3c2d554"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_profile-2.2.0rc1-sources.jar",
          "url": "permission_handler_android_profile-2.2.0rc1-sources.jar",
          "size": 18177,
          "sha512": "673bc0d22579ac8c7f7a50b04d3f47d4cdb85dbc8aa15bfcb371b64223d3ee8f535385b2e67dfa1230c825ecddb11e45e1a0b74410e608691074c11623d4f06e",
          "sha256": "3301b75b44b9f004580d559b28ab51dd9205289cc88ccc668ce8179f5bf24c67",
          "sha1": "7a9e4cb073bdd84100ad45b7d2c21b036815543f",
          "md5": "6347cb73f0ecc4fc5e825d6de82fca4e"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_profile-2.2.0rc1-javadoc.jar",
          "url": "permission_handler_android_profile-2.2.0rc1-javadoc.jar",
          "size": 264583,
          "sha512": "7ca833ff2f543d786af7828cdfb06cf1aeb6fe6821846241c38adffcbca7815446451c982de844650b82e2c8053e5d69c8deb79657c830ea44ab729ba89dae68",
          "sha256": "eb40dcc541d0ffe840edcc40ace622dcaa522eef7bb936a93fe86228d01f4e1e",
          "sha1": "4aefbf9c83e32ac5c5366fc41b87dc1665823a5a",
          "md5": "fb6dce1d3f86999139b10afd3fefbea7"
        }
      ]
    }
  ]
}
