{
  "formatVersion": "1.1",
  "component": {
    "group": "com.empactit.empactit_wifi",
    "module": "empactit_wifi_release",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0.aar",
          "url": "empactit_wifi_release-2.2.0.aar",
          "size": 3642,
          "sha512": "16aa87704e165ed613f2b6c4754c61bc6ff23d0013ff6452ac14477e62ee14ac4c2fdb7952b2463796c7272deeae92802d9c258a68625a5ff0d89c7c590700e1",
          "sha256": "f94c6a39f29ed77b48ab4a8e110bf72b23c833dd73d54100a760b8e7c4bdcaf9",
          "sha1": "748d0202c91bbc409367a9cb9e5b51d8b4f3f4ef",
          "md5": "b49ecef2e2c30c870550a02e18c5e1a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_release",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0.aar",
          "url": "empactit_wifi_release-2.2.0.aar",
          "size": 3642,
          "sha512": "16aa87704e165ed613f2b6c4754c61bc6ff23d0013ff6452ac14477e62ee14ac4c2fdb7952b2463796c7272deeae92802d9c258a68625a5ff0d89c7c590700e1",
          "sha256": "f94c6a39f29ed77b48ab4a8e110bf72b23c833dd73d54100a760b8e7c4bdcaf9",
          "sha1": "748d0202c91bbc409367a9cb9e5b51d8b4f3f4ef",
          "md5": "b49ecef2e2c30c870550a02e18c5e1a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0-sources.jar",
          "url": "empactit_wifi_release-2.2.0-sources.jar",
          "size": 2637,
          "sha512": "45f656e4e0fdf666b791c4e3a93e8a7376109a3630cd2fa1dbdd65fcc58b7926e09226e58e0e32e63b30ea3ebcdb0165a8a599434c7ee10d68185ffc66486c44",
          "sha256": "3b15e813eb358217d03c2b029e24572aba80138c8c54a4ed858a2e963b72b0f9",
          "sha1": "5f5321a4f78b12be6c775449dfde70ec7c17c3cc",
          "md5": "2c9848eae5dad965b0a7fe0ff44411fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "empactit_wifi_release-2.2.0-javadoc.jar",
          "url": "empactit_wifi_release-2.2.0-javadoc.jar",
          "size": 263924,
          "sha512": "c53d7e460356b5c58666c81fc58298d141e51334af0cbac849abb1f8398df2cc939401848f9b4b673f922f11302fd6bb6f7b89151c796b79a0650608d1fa196e",
          "sha256": "6d35624c52330d0eec54670633a1e54df57e322cf9ee62b628cd58346934d788",
          "sha1": "460b584bc53dbe9f32cbedf1509a993859b7f2d3",
          "md5": "bf4c4282c662e1c183e46d980f678e0a"
        }
      ]
    }
  ]
}
