{
  "formatVersion": "1.1",
  "component": {
    "group": "io.adaptant.labs.flutter_windowmanager",
    "module": "flutter_windowmanager_release",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_release-2.1.0.aar",
          "url": "flutter_windowmanager_release-2.1.0.aar",
          "size": 5620,
          "sha512": "c628b6700af3c3b74f2e7c9d3728e5a0ceb9d110d79041a545456cd03aac957edc55f4cce0892947a3156151806fc4bb193d7de349ade24c61ce08039b716b84",
          "sha256": "fca601dc4d4f65b827d5ef6ea866bcd4fd9c3bfa52a2b40a1ebe5a593d6c64d5",
          "sha1": "e5845a70637a59cc364f1997fb212bab1e9d31b9",
          "md5": "54231e50e1884e648ed1963c52a5d09a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_release-2.1.0.aar",
          "url": "flutter_windowmanager_release-2.1.0.aar",
          "size": 5620,
          "sha512": "c628b6700af3c3b74f2e7c9d3728e5a0ceb9d110d79041a545456cd03aac957edc55f4cce0892947a3156151806fc4bb193d7de349ade24c61ce08039b716b84",
          "sha256": "fca601dc4d4f65b827d5ef6ea866bcd4fd9c3bfa52a2b40a1ebe5a593d6c64d5",
          "sha1": "e5845a70637a59cc364f1997fb212bab1e9d31b9",
          "md5": "54231e50e1884e648ed1963c52a5d09a"
        }
      ]
    }
  ]
}
