{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_release",
    "version": "v1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-v1.1.0.aar",
          "url": "connectivity_plus_release-v1.1.0.aar",
          "size": 9033,
          "sha512": "45762e09ee8619f23f35cf24711ee5b401d3efa33b91e79d918a25def3ca21c189fc73734fa3407d1f0ce6d643adc2d73509097765786534a4376a4df3a23d53",
          "sha256": "7bf88c565285d39516acac2a8056871f4314817300ad0fc9699682e8715f395d",
          "sha1": "ef632a2536f205a9b43bf79a1089b26fafd9606a",
          "md5": "f274d7aa531b0384758fd0a2fe0a8ec7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-v1.1.0.aar",
          "url": "connectivity_plus_release-v1.1.0.aar",
          "size": 9033,
          "sha512": "45762e09ee8619f23f35cf24711ee5b401d3efa33b91e79d918a25def3ca21c189fc73734fa3407d1f0ce6d643adc2d73509097765786534a4376a4df3a23d53",
          "sha256": "7bf88c565285d39516acac2a8056871f4314817300ad0fc9699682e8715f395d",
          "sha1": "ef632a2536f205a9b43bf79a1089b26fafd9606a",
          "md5": "f274d7aa531b0384758fd0a2fe0a8ec7"
        }
      ]
    }
  ]
}
