{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-2.1.0.aar",
          "url": "url_launcher_android_profile-2.1.0.aar",
          "size": 23293,
          "sha512": "087febd6090aa59ed0373134a972b56ba59aeaac89ed711bf8eb60ea8b7003d0a5ccd37de2ad05fb19c3444c764926b780bdb9804606d5d6f05b47d813c72276",
          "sha256": "ca0830d79aaf01ebb3e94730fc57e3eb7fb6f78ae51473d58307ee39669c98c0",
          "sha1": "4135e049b9aa6eb6e7a7fb882d2da454f41ede2b",
          "md5": "224178c605f90977e65a9ab3ebf2ad31"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-2.1.0.aar",
          "url": "url_launcher_android_profile-2.1.0.aar",
          "size": 23293,
          "sha512": "087febd6090aa59ed0373134a972b56ba59aeaac89ed711bf8eb60ea8b7003d0a5ccd37de2ad05fb19c3444c764926b780bdb9804606d5d6f05b47d813c72276",
          "sha256": "ca0830d79aaf01ebb3e94730fc57e3eb7fb6f78ae51473d58307ee39669c98c0",
          "sha1": "4135e049b9aa6eb6e7a7fb882d2da454f41ede2b",
          "md5": "224178c605f90977e65a9ab3ebf2ad31"
        }
      ]
    }
  ]
}
