{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_release",
    "version": "v2.0.0rc4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-v2.0.0rc4.aar",
          "url": "connectivity_plus_release-v2.0.0rc4.aar",
          "size": 9913,
          "sha512": "d6337cc18c46074538d7df1a8fc650cebaa38d9c2b4ec03b7136bb2de33f3b5a0daefc8d1713faaec8478bae209311dc73e50c31618d7cbde5aa647e855e3c19",
          "sha256": "83d1ec3ed6a0aedee8cdde301b5e7bccdb4ebb0d5aa19bf41ff68dec9e1cdd3c",
          "sha1": "a92f6ec670e2ecf6e9dce56f9905a7b00680410c",
          "md5": "5339a1ffa1229f6a883b029684ab71d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-v2.0.0rc4.aar",
          "url": "connectivity_plus_release-v2.0.0rc4.aar",
          "size": 9913,
          "sha512": "d6337cc18c46074538d7df1a8fc650cebaa38d9c2b4ec03b7136bb2de33f3b5a0daefc8d1713faaec8478bae209311dc73e50c31618d7cbde5aa647e855e3c19",
          "sha256": "83d1ec3ed6a0aedee8cdde301b5e7bccdb4ebb0d5aa19bf41ff68dec9e1cdd3c",
          "sha1": "a92f6ec670e2ecf6e9dce56f9905a7b00680410c",
          "md5": "5339a1ffa1229f6a883b029684ab71d1"
        }
      ]
    }
  ]
}
