{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_release",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-2.1.2.aar",
          "url": "camera_android_release-2.1.2.aar",
          "size": 118626,
          "sha512": "e55c0e89531af746bff737323bb523c8313aab4f9c5c44928f0a2166c4755ee36208528075d094ece98d4fef9523e28d4d64bf278aa9406268dd9c03e7cb4013",
          "sha256": "920dc2ecb25ba8936c10b9a8bac00689a7388fa1d03d2b516cada2fb40238635",
          "sha1": "41feded9bbde9e1a2f1ae2b5f14f53b2a4f52692",
          "md5": "e2bdc36db0da9476d7e1c0219aca439f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-2.1.2.aar",
          "url": "camera_android_release-2.1.2.aar",
          "size": 118626,
          "sha512": "e55c0e89531af746bff737323bb523c8313aab4f9c5c44928f0a2166c4755ee36208528075d094ece98d4fef9523e28d4d64bf278aa9406268dd9c03e7cb4013",
          "sha256": "920dc2ecb25ba8936c10b9a8bac00689a7388fa1d03d2b516cada2fb40238635",
          "sha1": "41feded9bbde9e1a2f1ae2b5f14f53b2a4f52692",
          "md5": "e2bdc36db0da9476d7e1c0219aca439f"
        }
      ]
    }
  ]
}
