{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "2.2.0rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-2.2.0rc1.aar",
          "url": "device_info_plus_debug-2.2.0rc1.aar",
          "size": 7762,
          "sha512": "92e2911512f892edf424da0f66f681cca10ca17c26f2321b0031aed859813180361ae72fcd5dc4d33dc287f810e8bf549059b5e8653d8a0bf1f6dcf1b10d0690",
          "sha256": "31fcdc1fde60a21c1959957d5f08caa4ff786f11dc2aeaabb7bb6ea8d73b4ba8",
          "sha1": "36126eb119d4e5ac4d78be8cd837a9a9b6a214ff",
          "md5": "1d6a0379c6722d645ad0da7c8e1a57f4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-69c8c61792f04cc809dfef0c910414fb9afc06cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-2.2.0rc1.aar",
          "url": "device_info_plus_debug-2.2.0rc1.aar",
          "size": 7762,
          "sha512": "92e2911512f892edf424da0f66f681cca10ca17c26f2321b0031aed859813180361ae72fcd5dc4d33dc287f810e8bf549059b5e8653d8a0bf1f6dcf1b10d0690",
          "sha256": "31fcdc1fde60a21c1959957d5f08caa4ff786f11dc2aeaabb7bb6ea8d73b4ba8",
          "sha1": "36126eb119d4e5ac4d78be8cd837a9a9b6a214ff",
          "md5": "1d6a0379c6722d645ad0da7c8e1a57f4"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_debug-2.2.0rc1-sources.jar",
          "url": "device_info_plus_debug-2.2.0rc1-sources.jar",
          "size": 3125,
          "sha512": "b9cb00c45bc93bb579209e570cc6bccd93db4bc096aa171224af075e8692c8781fa658075ca0fac74487a49fa688512631128c1179a925ebcfc7e0df2ac1c49f",
          "sha256": "881c3ff7cebe7fa7dcbc12c9cd124932bc1986640af6e78c69608b8c0a68b939",
          "sha1": "baedb19f71c1d446920d5e7702e29ce5e368c7d4",
          "md5": "cd8cd56bd2b0956e8e0eb8238a55e8dc"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_debug-2.2.0rc1-javadoc.jar",
          "url": "device_info_plus_debug-2.2.0rc1-javadoc.jar",
          "size": 260831,
          "sha512": "0bec0cbb889306edd8b92f2141dd41c0b953a7526cfb56b3a518dd21c11552ac607ee732196e9781e6e6a7dbd4677c1e5a4a3fb52f85bf850bf918b5d4579bd6",
          "sha256": "9393836861160e7a072b789f9d50c045f3f6c2b89cd92942f9748f165624417c",
          "sha1": "652bf75b453cfc4ae97e2538a43fd999cb8ec7b9",
          "md5": "a4739b3702bdece7ed4f726358befb40"
        }
      ]
    }
  ]
}
