{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_profile",
    "version": "v1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "v1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-v1.1.0.aar",
          "url": "flutter_profile-v1.1.0.aar",
          "size": 38937032,
          "sha512": "00dd135f78915bfff86db83dbcc45ed42ebf71acbfb34d45276c3071b454a3282bb4b923149f7e364ee8585e8aa21b6cab0af6425a8d6200f53f56fbeb387deb",
          "sha256": "cdbd19a3150b930446fffe569fcdd4cfdc39a002bc7eb716d06c4334e77552ce",
          "sha1": "f1048f79af1cc2e95b5a303d3df0c89fc8bdd7f6",
          "md5": "bbdcef583eaef4326b64e55b65784de3"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "v1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-v1.1.0.aar",
          "url": "flutter_profile-v1.1.0.aar",
          "size": 38937032,
          "sha512": "00dd135f78915bfff86db83dbcc45ed42ebf71acbfb34d45276c3071b454a3282bb4b923149f7e364ee8585e8aa21b6cab0af6425a8d6200f53f56fbeb387deb",
          "sha256": "cdbd19a3150b930446fffe569fcdd4cfdc39a002bc7eb716d06c4334e77552ce",
          "sha1": "f1048f79af1cc2e95b5a303d3df0c89fc8bdd7f6",
          "md5": "bbdcef583eaef4326b64e55b65784de3"
        }
      ]
    }
  ]
}
