{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-2.1.0.aar",
          "url": "url_launcher_android_release-2.1.0.aar",
          "size": 23292,
          "sha512": "0f025eded0856c96ad4aacb213a8015ce3e65222ce7285e9e0451ecaddf0e66efe77a3194ffe04bed2f457c67a4a795cb8928224a49ff4edc7b20bbcfe0a0861",
          "sha256": "cc7b6d3befa2283e433545d4440582f31131ac53ace9d70e87cc1fb3b420de76",
          "sha1": "adf0fe12777f16a63b11bafd8ed962cda68626dc",
          "md5": "eff44cca78d015f8ad0ed31531e49f33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-04817c99c9fd4956f27505204f7e344335810aed"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-2.1.0.aar",
          "url": "url_launcher_android_release-2.1.0.aar",
          "size": 23292,
          "sha512": "0f025eded0856c96ad4aacb213a8015ce3e65222ce7285e9e0451ecaddf0e66efe77a3194ffe04bed2f457c67a4a795cb8928224a49ff4edc7b20bbcfe0a0861",
          "sha256": "cc7b6d3befa2283e433545d4440582f31131ac53ace9d70e87cc1fb3b420de76",
          "sha1": "adf0fe12777f16a63b11bafd8ed962cda68626dc",
          "md5": "eff44cca78d015f8ad0ed31531e49f33"
        }
      ]
    }
  ]
}
