{
  "formatVersion": "1.1",
  "component": {
    "group": "net.touchcapture.qr.flutterqr",
    "module": "qr_code_scanner_profile",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-2.1.4.aar",
          "url": "qr_code_scanner_profile-2.1.4.aar",
          "size": 36461,
          "sha512": "a3e50de035b2ec26c68554c871f27e4e77606888b963251fa9d3bccacaf8ebd4cc628f830b16f22a1328032eb118a2fdd3c1cab4c0995819fa8582d8767ad924",
          "sha256": "a725a0407f9033236ebb24c48820d6d5e8db092b9e268a0bb96f4d6063454ca5",
          "sha1": "a9436ce5f60bd5f15a5d32db8f01ecd33c00805d",
          "md5": "287d7d91afd14d848ca90a9fa2475837"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-2.1.4.aar",
          "url": "qr_code_scanner_profile-2.1.4.aar",
          "size": 36461,
          "sha512": "a3e50de035b2ec26c68554c871f27e4e77606888b963251fa9d3bccacaf8ebd4cc628f830b16f22a1328032eb118a2fdd3c1cab4c0995819fa8582d8767ad924",
          "sha256": "a725a0407f9033236ebb24c48820d6d5e8db092b9e268a0bb96f4d6063454ca5",
          "sha1": "a9436ce5f60bd5f15a5d32db8f01ecd33c00805d",
          "md5": "287d7d91afd14d848ca90a9fa2475837"
        }
      ]
    }
  ]
}
