{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "v1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-v1.0.1.aar",
          "url": "webview_flutter_android_profile-v1.0.1.aar",
          "size": 107070,
          "sha512": "8450b137388513230f8af9eb3ac45460d5f837f75349fdd6a0048fab2a6a1b87f839852a161db3a2770c13d9cd50a633104830435b9a8222e9a3080b56693da8",
          "sha256": "90e860e5f3160fd104ae4263e4b314624c41cd900e9fa9a94d8fec55b1edfbd7",
          "sha1": "c5022bf460599232cd860d0225f1488ba8f04392",
          "md5": "df04418f36bd85e24632d56ce3ac9c31"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-v1.0.1.aar",
          "url": "webview_flutter_android_profile-v1.0.1.aar",
          "size": 107070,
          "sha512": "8450b137388513230f8af9eb3ac45460d5f837f75349fdd6a0048fab2a6a1b87f839852a161db3a2770c13d9cd50a633104830435b9a8222e9a3080b56693da8",
          "sha256": "90e860e5f3160fd104ae4263e4b314624c41cd900e9fa9a94d8fec55b1edfbd7",
          "sha1": "c5022bf460599232cd860d0225f1488ba8f04392",
          "md5": "df04418f36bd85e24632d56ce3ac9c31"
        }
      ]
    }
  ]
}
