{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-2.1.4.aar",
          "url": "webview_flutter_android_release-2.1.4.aar",
          "size": 106267,
          "sha512": "e834cfa6f8b25a533229a1b6d0e893475f4d83c920bc45cb58cda5c46bfeb33ed47b2aba93cad61806070737105b478de8728daf7f77b69c8a636fae250960cd",
          "sha256": "10c84c5853ac0c45e79d92284e9ae10697ea712deb674ded02447a550879d2e3",
          "sha1": "9c9f06ca08d3a18ced78ddc451ecfaade010a1b9",
          "md5": "51f8b0964389de20c4d36367db9b04d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-2.1.4.aar",
          "url": "webview_flutter_android_release-2.1.4.aar",
          "size": 106267,
          "sha512": "e834cfa6f8b25a533229a1b6d0e893475f4d83c920bc45cb58cda5c46bfeb33ed47b2aba93cad61806070737105b478de8728daf7f77b69c8a636fae250960cd",
          "sha256": "10c84c5853ac0c45e79d92284e9ae10697ea712deb674ded02447a550879d2e3",
          "sha1": "9c9f06ca08d3a18ced78ddc451ecfaade010a1b9",
          "md5": "51f8b0964389de20c4d36367db9b04d7"
        }
      ]
    }
  ]
}
