{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pay_android",
    "module": "pay_android_profile",
    "version": "v1.1.1h",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_profile-v1.1.1h.aar",
          "url": "pay_android_profile-v1.1.1h.aar",
          "size": 20366,
          "sha512": "6669484103553e04d940bf154f483672a4955d22f60f82d32186ea1523aa34900dee5c855281c233bd77f1a41db11ee6491e7a27a3aeb21855b45fc30c1cc74b",
          "sha256": "0deb3d6bef5f4d8eead6a1230e9f49a68c97c4dcadd0bcb75d8fb93cedc9974d",
          "sha1": "a6e3b39fdf138bd177d45402c233a37935dbba43",
          "md5": "c3e981a7d87190d4eb3ed913f7d55cee"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_profile-v1.1.1h.aar",
          "url": "pay_android_profile-v1.1.1h.aar",
          "size": 20366,
          "sha512": "6669484103553e04d940bf154f483672a4955d22f60f82d32186ea1523aa34900dee5c855281c233bd77f1a41db11ee6491e7a27a3aeb21855b45fc30c1cc74b",
          "sha256": "0deb3d6bef5f4d8eead6a1230e9f49a68c97c4dcadd0bcb75d8fb93cedc9974d",
          "sha1": "a6e3b39fdf138bd177d45402c233a37935dbba43",
          "md5": "c3e981a7d87190d4eb3ed913f7d55cee"
        }
      ]
    }
  ]
}
