{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flutternetwork.wifi.wifi_scan",
    "module": "wifi_scan_profile",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_profile-2.1.4.aar",
          "url": "wifi_scan_profile-2.1.4.aar",
          "size": 19120,
          "sha512": "cf97bd3bad5cac60121c94e9d0b51a95784064e288284d232a6fd2962e452f9fc94e14d034e07691aa12dd682c8385eb84d54f01f034c8b6610b52338a0fb23f",
          "sha256": "b227f79b5d9b46839658e59eb940fd5291fc2eaae2275d27da850d6468ddf03f",
          "sha1": "250b3e1de3f7de03171b25088b2595388c4c9dab",
          "md5": "e0b61ee2582cc9802d2752a3f843dcf9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_scan_profile-2.1.4.aar",
          "url": "wifi_scan_profile-2.1.4.aar",
          "size": 19120,
          "sha512": "cf97bd3bad5cac60121c94e9d0b51a95784064e288284d232a6fd2962e452f9fc94e14d034e07691aa12dd682c8385eb84d54f01f034c8b6610b52338a0fb23f",
          "sha256": "b227f79b5d9b46839658e59eb940fd5291fc2eaae2275d27da850d6468ddf03f",
          "sha1": "250b3e1de3f7de03171b25088b2595388c4c9dab",
          "md5": "e0b61ee2582cc9802d2752a3f843dcf9"
        }
      ]
    }
  ]
}
