{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geocoding",
    "module": "geocoding_android_profile",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "geocoding_android_profile-2.1.2.aar",
          "url": "geocoding_android_profile-2.1.2.aar",
          "size": 10500,
          "sha512": "312cc0c2ca4e6fd93d810e816374458191318d814729ec45998f0a4561d7e24426da5b2ec4498e6a227c8ac75b3515134dca5bd2406c869338f6f6a583b730bc",
          "sha256": "3a7b574ce35116b9f4a9b4a0b75afb4984c476891aa7bdca306d4d446b41f164",
          "sha1": "fb8dd0fd12f629964180fa0e5164e66f930a6ed3",
          "md5": "e2bb63be95887092b09a1a96f29adab1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "geocoding_android_profile-2.1.2.aar",
          "url": "geocoding_android_profile-2.1.2.aar",
          "size": 10500,
          "sha512": "312cc0c2ca4e6fd93d810e816374458191318d814729ec45998f0a4561d7e24426da5b2ec4498e6a227c8ac75b3515134dca5bd2406c869338f6f6a583b730bc",
          "sha256": "3a7b574ce35116b9f4a9b4a0b75afb4984c476891aa7bdca306d4d446b41f164",
          "sha1": "fb8dd0fd12f629964180fa0e5164e66f930a6ed3",
          "md5": "e2bb63be95887092b09a1a96f29adab1"
        }
      ]
    }
  ]
}
