{
  "formatVersion": "1.1",
  "component": {
    "group": "net.touchcapture.qr.flutterqr",
    "module": "qr_code_scanner_profile",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-2.0.2.aar",
          "url": "qr_code_scanner_profile-2.0.2.aar",
          "size": 36460,
          "sha512": "e93e351561f89cb6ba1e3dc8c87925f58c0e04cbe542ef50fbbcad6fedca7eebd22e29352d2fc1a5515e85fc3c362d67515bb44aafdedcbb418247e2aec0a4de",
          "sha256": "9f071e5788e8647c74eff8349891084d56c55b79a5586f88350ffee7db8f6771",
          "sha1": "8c38fb6c70b0513cf320b80234c86f6c73e81f01",
          "md5": "41253b6381f3135e55dbff4b973b5b95"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "qr_code_scanner_profile-2.0.2.aar",
          "url": "qr_code_scanner_profile-2.0.2.aar",
          "size": 36460,
          "sha512": "e93e351561f89cb6ba1e3dc8c87925f58c0e04cbe542ef50fbbcad6fedca7eebd22e29352d2fc1a5515e85fc3c362d67515bb44aafdedcbb418247e2aec0a4de",
          "sha256": "9f071e5788e8647c74eff8349891084d56c55b79a5586f88350ffee7db8f6771",
          "sha1": "8c38fb6c70b0513cf320b80234c86f6c73e81f01",
          "md5": "41253b6381f3135e55dbff4b973b5b95"
        }
      ]
    }
  ]
}
