{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hlsr.rodeohouston.flutter_rodeo_carnival_module",
    "module": "flutter_profile",
    "version": "v1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "v1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-v1.1.2.aar",
          "url": "flutter_profile-v1.1.2.aar",
          "size": 38950671,
          "sha512": "0b70e230cd5b5197707b60622b2b22f901634bfa9960044d10834bc3eaf45382c0c3e96e78b97f07f0ae3623d869921aae489ea7b082710718027583d907f5bd",
          "sha256": "e3b0be968b8a062f26dfdb9eb8093586076f67b11767a11d5394f494bf88ae0f",
          "sha1": "b1505cb07d26a19dec232761098828c2f6905db3",
          "md5": "4b539ce96b837405837dbd875d354e4e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.danieldallos.storeredirect",
          "module": "store_redirect_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.flutternetwork.wifi.wifi_scan",
          "module": "wifi_scan_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.empactit.empactit_wifi",
          "module": "empactit_wifi_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.baseflow.geocoding",
          "module": "geocoding_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.alternadom.wifiiot",
          "module": "wifi_iot_profile",
          "version": {
            "requires": "v1.1.2"
          }
        },
        {
          "group": "com.iyaffle.launchreview",
          "module": "launch_review_profile",
          "version": {
            "requires": "v1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-v1.1.2.aar",
          "url": "flutter_profile-v1.1.2.aar",
          "size": 38950671,
          "sha512": "0b70e230cd5b5197707b60622b2b22f901634bfa9960044d10834bc3eaf45382c0c3e96e78b97f07f0ae3623d869921aae489ea7b082710718027583d907f5bd",
          "sha256": "e3b0be968b8a062f26dfdb9eb8093586076f67b11767a11d5394f494bf88ae0f",
          "sha1": "b1505cb07d26a19dec232761098828c2f6905db3",
          "md5": "4b539ce96b837405837dbd875d354e4e"
        }
      ]
    }
  ]
}
